<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>BlockingObservableNextTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.internal.operators.observable</a> &gt; <span class="el_source">BlockingObservableNextTest.java</span></div><h1>BlockingObservableNextTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.internal.operators.observable;

import static org.junit.Assert.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;

import org.junit.*;

import io.reactivex.*;
import io.reactivex.Observable;
import io.reactivex.Observer;
import io.reactivex.disposables.*;
import io.reactivex.exceptions.TestException;
import io.reactivex.internal.operators.observable.BlockingObservableNext.NextObserver;
import io.reactivex.plugins.RxJavaPlugins;
import io.reactivex.processors.BehaviorProcessor;
import io.reactivex.schedulers.Schedulers;
import io.reactivex.subjects.*;

<span class="fc" id="L35">public class BlockingObservableNextTest {</span>

    private void fireOnNextInNewThread(final Subject&lt;String&gt; o, final String value) {
<span class="fc" id="L38">        new Thread() {</span>
            @Override
            public void run() {
                try {
<span class="fc" id="L42">                    Thread.sleep(500);</span>
<span class="nc" id="L43">                } catch (InterruptedException e) {</span>
                    // ignore
<span class="fc" id="L45">                }</span>
<span class="fc" id="L46">                o.onNext(value);</span>
<span class="fc" id="L47">            }</span>
<span class="fc" id="L48">        }.start();</span>
<span class="fc" id="L49">    }</span>

    private void fireOnErrorInNewThread(final Subject&lt;String&gt; o) {
<span class="fc" id="L52">        new Thread() {</span>
            @Override
            public void run() {
                try {
<span class="fc" id="L56">                    Thread.sleep(500);</span>
<span class="nc" id="L57">                } catch (InterruptedException e) {</span>
                    // ignore
<span class="fc" id="L59">                }</span>
<span class="fc" id="L60">                o.onError(new TestException());</span>
<span class="fc" id="L61">            }</span>
<span class="fc" id="L62">        }.start();</span>
<span class="fc" id="L63">    }</span>

    static &lt;T&gt; Iterable&lt;T&gt; next(ObservableSource&lt;T&gt; source) {
<span class="fc" id="L66">        return new BlockingObservableNext&lt;T&gt;(source);</span>
    }

    @Test
    public void testNext() {
<span class="fc" id="L71">        Subject&lt;String&gt; obs = PublishSubject.create();</span>
<span class="fc" id="L72">        Iterator&lt;String&gt; it = next(obs).iterator();</span>
<span class="fc" id="L73">        fireOnNextInNewThread(obs, &quot;one&quot;);</span>
<span class="fc" id="L74">        assertTrue(it.hasNext());</span>
<span class="fc" id="L75">        assertEquals(&quot;one&quot;, it.next());</span>

<span class="fc" id="L77">        fireOnNextInNewThread(obs, &quot;two&quot;);</span>
<span class="fc" id="L78">        assertTrue(it.hasNext());</span>
<span class="fc" id="L79">        assertEquals(&quot;two&quot;, it.next());</span>

<span class="fc" id="L81">        fireOnNextInNewThread(obs, &quot;three&quot;);</span>
        try {
<span class="fc" id="L83">            assertEquals(&quot;three&quot;, it.next());</span>
<span class="nc" id="L84">        } catch (NoSuchElementException e) {</span>
<span class="nc" id="L85">            fail(&quot;Calling next() without hasNext() should wait for next fire&quot;);</span>
<span class="fc" id="L86">        }</span>

<span class="fc" id="L88">        obs.onComplete();</span>
<span class="fc" id="L89">        assertFalse(it.hasNext());</span>
        try {
<span class="nc" id="L91">            it.next();</span>
<span class="nc" id="L92">            fail(&quot;At the end of an iterator should throw a NoSuchElementException&quot;);</span>
<span class="fc" id="L93">        } catch (NoSuchElementException e) {</span>
<span class="nc" id="L94">        }</span>

        // If the Observable is completed, hasNext always returns false and next always throw a NoSuchElementException.
<span class="fc" id="L97">        assertFalse(it.hasNext());</span>
        try {
<span class="nc" id="L99">            it.next();</span>
<span class="nc" id="L100">            fail(&quot;At the end of an iterator should throw a NoSuchElementException&quot;);</span>
<span class="fc" id="L101">        } catch (NoSuchElementException e) {</span>
<span class="nc" id="L102">        }</span>
<span class="fc" id="L103">    }</span>

    @Test
    public void testNextWithError() {
<span class="fc" id="L107">        Subject&lt;String&gt; obs = PublishSubject.create();</span>
<span class="fc" id="L108">        Iterator&lt;String&gt; it = next(obs).iterator();</span>
<span class="fc" id="L109">        fireOnNextInNewThread(obs, &quot;one&quot;);</span>
<span class="fc" id="L110">        assertTrue(it.hasNext());</span>
<span class="fc" id="L111">        assertEquals(&quot;one&quot;, it.next());</span>

<span class="fc" id="L113">        fireOnErrorInNewThread(obs);</span>
        try {
<span class="nc" id="L115">            it.hasNext();</span>
<span class="nc" id="L116">            fail(&quot;Expected an TestException&quot;);</span>
<span class="fc" id="L117">        } catch (TestException e) {</span>
<span class="nc" id="L118">        }</span>

<span class="fc" id="L120">        assertErrorAfterObservableFail(it);</span>
<span class="fc" id="L121">    }</span>

    @Test
    public void testNextWithEmpty() {
<span class="fc" id="L125">        Observable&lt;String&gt; obs = Observable.&lt;String&gt; empty().observeOn(Schedulers.newThread());</span>
<span class="fc" id="L126">        Iterator&lt;String&gt; it = next(obs).iterator();</span>

<span class="fc" id="L128">        assertFalse(it.hasNext());</span>
        try {
<span class="nc" id="L130">            it.next();</span>
<span class="nc" id="L131">            fail(&quot;At the end of an iterator should throw a NoSuchElementException&quot;);</span>
<span class="fc" id="L132">        } catch (NoSuchElementException e) {</span>
<span class="nc" id="L133">        }</span>

        // If the Observable is completed, hasNext always returns false and next always throw a NoSuchElementException.
<span class="fc" id="L136">        assertFalse(it.hasNext());</span>
        try {
<span class="nc" id="L138">            it.next();</span>
<span class="nc" id="L139">            fail(&quot;At the end of an iterator should throw a NoSuchElementException&quot;);</span>
<span class="fc" id="L140">        } catch (NoSuchElementException e) {</span>
<span class="nc" id="L141">        }</span>
<span class="fc" id="L142">    }</span>

    @Test
    public void testOnError() throws Throwable {
<span class="fc" id="L146">        Subject&lt;String&gt; obs = PublishSubject.create();</span>
<span class="fc" id="L147">        Iterator&lt;String&gt; it = next(obs).iterator();</span>

<span class="fc" id="L149">        obs.onError(new TestException());</span>
        try {
<span class="nc" id="L151">            it.hasNext();</span>
<span class="nc" id="L152">            fail(&quot;Expected an TestException&quot;);</span>
<span class="fc" id="L153">        } catch (TestException e) {</span>
            // successful
<span class="nc" id="L155">        }</span>

<span class="fc" id="L157">        assertErrorAfterObservableFail(it);</span>
<span class="fc" id="L158">    }</span>

    @Test
    public void testOnErrorInNewThread() {
<span class="fc" id="L162">        Subject&lt;String&gt; obs = PublishSubject.create();</span>
<span class="fc" id="L163">        Iterator&lt;String&gt; it = next(obs).iterator();</span>

<span class="fc" id="L165">        fireOnErrorInNewThread(obs);</span>

        try {
<span class="nc" id="L168">            it.hasNext();</span>
<span class="nc" id="L169">            fail(&quot;Expected an TestException&quot;);</span>
<span class="fc" id="L170">        } catch (TestException e) {</span>
            // successful
<span class="nc" id="L172">        }</span>

<span class="fc" id="L174">        assertErrorAfterObservableFail(it);</span>
<span class="fc" id="L175">    }</span>

    private void assertErrorAfterObservableFail(Iterator&lt;String&gt; it) {
        // After the Observable fails, hasNext and next always throw the exception.
        try {
<span class="nc" id="L180">            it.hasNext();</span>
<span class="nc" id="L181">            fail(&quot;hasNext should throw a TestException&quot;);</span>
<span class="fc" id="L182">        } catch (TestException e) {</span>
<span class="nc" id="L183">        }</span>
        try {
<span class="nc" id="L185">            it.next();</span>
<span class="nc" id="L186">            fail(&quot;next should throw a TestException&quot;);</span>
<span class="fc" id="L187">        } catch (TestException e) {</span>
<span class="nc" id="L188">        }</span>
<span class="fc" id="L189">    }</span>

    @Test
    public void testNextWithOnlyUsingNextMethod() {
<span class="fc" id="L193">        Subject&lt;String&gt; obs = PublishSubject.create();</span>
<span class="fc" id="L194">        Iterator&lt;String&gt; it = next(obs).iterator();</span>
<span class="fc" id="L195">        fireOnNextInNewThread(obs, &quot;one&quot;);</span>
<span class="fc" id="L196">        assertEquals(&quot;one&quot;, it.next());</span>

<span class="fc" id="L198">        fireOnNextInNewThread(obs, &quot;two&quot;);</span>
<span class="fc" id="L199">        assertEquals(&quot;two&quot;, it.next());</span>

<span class="fc" id="L201">        obs.onComplete();</span>
        try {
<span class="nc" id="L203">            it.next();</span>
<span class="nc" id="L204">            fail(&quot;At the end of an iterator should throw a NoSuchElementException&quot;);</span>
<span class="fc" id="L205">        } catch (NoSuchElementException e) {</span>
<span class="nc" id="L206">        }</span>
<span class="fc" id="L207">    }</span>

    @Test
    public void testNextWithCallingHasNextMultipleTimes() {
<span class="fc" id="L211">        Subject&lt;String&gt; obs = PublishSubject.create();</span>
<span class="fc" id="L212">        Iterator&lt;String&gt; it = next(obs).iterator();</span>
<span class="fc" id="L213">        fireOnNextInNewThread(obs, &quot;one&quot;);</span>
<span class="fc" id="L214">        assertTrue(it.hasNext());</span>
<span class="fc" id="L215">        assertTrue(it.hasNext());</span>
<span class="fc" id="L216">        assertTrue(it.hasNext());</span>
<span class="fc" id="L217">        assertTrue(it.hasNext());</span>
<span class="fc" id="L218">        assertEquals(&quot;one&quot;, it.next());</span>

<span class="fc" id="L220">        obs.onComplete();</span>
        try {
<span class="nc" id="L222">            it.next();</span>
<span class="nc" id="L223">            fail(&quot;At the end of an iterator should throw a NoSuchElementException&quot;);</span>
<span class="fc" id="L224">        } catch (NoSuchElementException e) {</span>
<span class="nc" id="L225">        }</span>
<span class="fc" id="L226">    }</span>

    /**
     * Confirm that no buffering or blocking of the Observable onNext calls occurs and it just grabs the next emitted value.
     * &lt;p/&gt;
     * This results in output such as =&gt; a: 1 b: 2 c: 89
     *
     * @throws Throwable some method call is declared throws
     */
    @Test
    public void testNoBufferingOrBlockingOfSequence() throws Throwable {
<span class="fc" id="L237">        int repeat = 0;</span>
        for (;;) {
<span class="fc" id="L239">            final SerialDisposable task = new SerialDisposable();</span>
            try {
<span class="fc" id="L241">                final CountDownLatch finished = new CountDownLatch(1);</span>
<span class="fc" id="L242">                final int COUNT = 30;</span>
<span class="fc" id="L243">                final CountDownLatch timeHasPassed = new CountDownLatch(COUNT);</span>
<span class="fc" id="L244">                final AtomicBoolean running = new AtomicBoolean(true);</span>
<span class="fc" id="L245">                final AtomicInteger count = new AtomicInteger(0);</span>
<span class="fc" id="L246">                final Observable&lt;Integer&gt; obs = Observable.unsafeCreate(new ObservableSource&lt;Integer&gt;() {</span>

                    @Override
                    public void subscribe(final Observer&lt;? super Integer&gt; o) {
<span class="fc" id="L250">                        o.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L251">                        task.replace(Schedulers.single().scheduleDirect(new Runnable() {</span>

                            @Override
                            public void run() {
                                try {
<span class="pc bpc" id="L256" title="1 of 4 branches missed.">                                    while (running.get() &amp;&amp; !task.isDisposed()) {</span>
<span class="fc" id="L257">                                        o.onNext(count.incrementAndGet());</span>
<span class="fc" id="L258">                                        timeHasPassed.countDown();</span>
                                    }
<span class="fc" id="L260">                                    o.onComplete();</span>
<span class="nc" id="L261">                                } catch (Throwable e) {</span>
<span class="nc" id="L262">                                    o.onError(e);</span>
                                } finally {
<span class="fc" id="L264">                                    finished.countDown();</span>
                                }
<span class="fc" id="L266">                            }</span>
                        }));
<span class="fc" id="L268">                    }</span>

                });

<span class="fc" id="L272">                Iterator&lt;Integer&gt; it = next(obs).iterator();</span>

<span class="fc" id="L274">                assertTrue(it.hasNext());</span>
<span class="fc" id="L275">                int a = it.next();</span>
<span class="fc" id="L276">                assertTrue(it.hasNext());</span>
<span class="fc" id="L277">                int b = it.next();</span>
                // we should have a different value
<span class="pc bpc" id="L279" title="1 of 2 branches missed.">                assertTrue(&quot;a and b should be different&quot;, a != b);</span>

                // wait for some time (if times out we are blocked somewhere so fail ... set very high for very slow, constrained machines)
<span class="fc" id="L282">                timeHasPassed.await(8000, TimeUnit.MILLISECONDS);</span>

<span class="fc" id="L284">                assertTrue(it.hasNext());</span>
<span class="fc" id="L285">                int c = it.next();</span>

<span class="pc bpc" id="L287" title="1 of 2 branches missed.">                assertTrue(&quot;c should not just be the next in sequence&quot;, c != (b + 1));</span>
<span class="pc bpc" id="L288" title="1 of 2 branches missed.">                assertTrue(&quot;expected that c [&quot; + c + &quot;] is higher than or equal to &quot; + COUNT, c &gt;= COUNT);</span>

<span class="fc" id="L290">                assertTrue(it.hasNext());</span>
<span class="fc" id="L291">                int d = it.next();</span>
<span class="pc bpc" id="L292" title="1 of 2 branches missed.">                assertTrue(d &gt; c);</span>

                // shut down the thread
<span class="fc" id="L295">                running.set(false);</span>

<span class="fc" id="L297">                finished.await();</span>

<span class="fc" id="L299">                assertFalse(it.hasNext());</span>

<span class="fc" id="L301">                System.out.println(&quot;a: &quot; + a + &quot; b: &quot; + b + &quot; c: &quot; + c);</span>
                break;
<span class="nc" id="L303">            } catch (AssertionError ex) {</span>
<span class="nc bnc" id="L304" title="All 2 branches missed.">                if (++repeat == 3) {</span>
<span class="nc" id="L305">                    throw ex;</span>
                }
<span class="nc" id="L307">                Thread.sleep((int)(1000 * Math.pow(2, repeat - 1)));</span>
            } finally {
<span class="fc" id="L309">                task.dispose();</span>
            }
<span class="nc" id="L311">        }</span>
<span class="fc" id="L312">    }</span>

    @Test /* (timeout = 8000) */
    public void testSingleSourceManyIterators() throws InterruptedException {
<span class="fc" id="L316">        Observable&lt;Long&gt; o = Observable.interval(250, TimeUnit.MILLISECONDS);</span>
<span class="fc" id="L317">        PublishSubject&lt;Integer&gt; terminal = PublishSubject.create();</span>
<span class="fc" id="L318">        Observable&lt;Long&gt; source = o.takeUntil(terminal);</span>

<span class="fc" id="L320">        Iterable&lt;Long&gt; iter = source.blockingNext();</span>

<span class="fc bfc" id="L322" title="All 2 branches covered.">        for (int j = 0; j &lt; 3; j++) {</span>
<span class="fc" id="L323">            BlockingObservableNext.NextIterator&lt;Long&gt; it = (BlockingObservableNext.NextIterator&lt;Long&gt;)iter.iterator();</span>

<span class="fc bfc" id="L325" title="All 2 branches covered.">            for (long i = 0; i &lt; 10; i++) {</span>
<span class="fc" id="L326">                Assert.assertEquals(true, it.hasNext());</span>
<span class="fc" id="L327">                Assert.assertEquals(j + &quot;th iteration next&quot;, Long.valueOf(i), it.next());</span>
            }
<span class="fc" id="L329">            terminal.onNext(1);</span>
        }
<span class="fc" id="L331">    }</span>

    @Test
    public void testSynchronousNext() {
<span class="fc" id="L335">        assertEquals(1, BehaviorProcessor.createDefault(1).take(1).blockingSingle().intValue());</span>
<span class="fc" id="L336">        assertEquals(2, BehaviorProcessor.createDefault(2).blockingIterable().iterator().next().intValue());</span>
<span class="fc" id="L337">        assertEquals(3, BehaviorProcessor.createDefault(3).blockingNext().iterator().next().intValue());</span>
<span class="fc" id="L338">    }</span>

    @Test
    public void interrupt() {
<span class="fc" id="L342">        Iterator&lt;Object&gt; it = Observable.never().blockingNext().iterator();</span>

        try {
<span class="fc" id="L345">            Thread.currentThread().interrupt();</span>
<span class="nc" id="L346">            it.next();</span>
<span class="fc" id="L347">        } catch (RuntimeException ex) {</span>
<span class="fc" id="L348">            assertTrue(ex.toString(), ex.getCause() instanceof InterruptedException);</span>
<span class="nc" id="L349">        }</span>
<span class="fc" id="L350">    }</span>

    @Test(expected = UnsupportedOperationException.class)
    public void remove() {
<span class="nc" id="L354">        Observable.never().blockingNext().iterator().remove();</span>
<span class="nc" id="L355">    }</span>

    @Test
    public void nextObserverError() {
<span class="fc" id="L359">        NextObserver&lt;Integer&gt; no = new NextObserver&lt;Integer&gt;();</span>

<span class="fc" id="L361">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L363">            no.onError(new TestException());</span>

<span class="fc" id="L365">            TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L367">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L369">    }</span>

    @Test
    public void nextObserverOnNext() throws Exception {
<span class="fc" id="L373">        NextObserver&lt;Integer&gt; no = new NextObserver&lt;Integer&gt;();</span>

<span class="fc" id="L375">        no.setWaiting();</span>
<span class="fc" id="L376">        no.onNext(Notification.createOnNext(1));</span>

<span class="fc" id="L378">        no.setWaiting();</span>
<span class="fc" id="L379">        no.onNext(Notification.createOnNext(1));</span>

<span class="fc" id="L381">        assertEquals(1, no.takeNext().getValue().intValue());</span>
<span class="fc" id="L382">    }</span>

    @Test
    public void nextObserverOnCompleteOnNext() throws Exception {
<span class="fc" id="L386">        NextObserver&lt;Integer&gt; no = new NextObserver&lt;Integer&gt;();</span>

<span class="fc" id="L388">        no.setWaiting();</span>
<span class="fc" id="L389">        no.onNext(Notification.&lt;Integer&gt;createOnComplete());</span>

<span class="fc" id="L391">        no.setWaiting();</span>
<span class="fc" id="L392">        no.onNext(Notification.createOnNext(1));</span>

<span class="fc" id="L394">        assertTrue(no.takeNext().isOnComplete());</span>
<span class="fc" id="L395">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>