<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>ObservableOnExceptionResumeNextViaObservableTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.internal.operators.observable</a> &gt; <span class="el_source">ObservableOnExceptionResumeNextViaObservableTest.java</span></div><h1>ObservableOnExceptionResumeNextViaObservableTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.internal.operators.observable;

import static org.junit.Assert.fail;
import static org.mockito.Mockito.*;

import org.junit.Test;
import org.mockito.Mockito;

import io.reactivex.*;
import io.reactivex.disposables.*;
import io.reactivex.functions.Function;
import io.reactivex.observers.TestObserver;
import io.reactivex.schedulers.Schedulers;

<span class="fc" id="L28">public class ObservableOnExceptionResumeNextViaObservableTest {</span>

    @Test
    public void testResumeNextWithException() {
        // Trigger failure on second element
<span class="fc" id="L33">        TestObservable f = new TestObservable(&quot;one&quot;, &quot;EXCEPTION&quot;, &quot;two&quot;, &quot;three&quot;);</span>
<span class="fc" id="L34">        Observable&lt;String&gt; w = Observable.unsafeCreate(f);</span>
<span class="fc" id="L35">        Observable&lt;String&gt; resume = Observable.just(&quot;twoResume&quot;, &quot;threeResume&quot;);</span>
<span class="fc" id="L36">        Observable&lt;String&gt; observable = w.onExceptionResumeNext(resume);</span>

<span class="fc" id="L38">        Observer&lt;String&gt; observer = TestHelper.mockObserver();</span>
<span class="fc" id="L39">        observable.subscribe(observer);</span>

        try {
<span class="fc" id="L42">            f.t.join();</span>
<span class="nc" id="L43">        } catch (InterruptedException e) {</span>
<span class="nc" id="L44">            fail(e.getMessage());</span>
<span class="fc" id="L45">        }</span>

<span class="fc" id="L47">        verify(observer).onSubscribe((Disposable)any());</span>
<span class="fc" id="L48">        verify(observer, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L49">        verify(observer, Mockito.never()).onNext(&quot;two&quot;);</span>
<span class="fc" id="L50">        verify(observer, Mockito.never()).onNext(&quot;three&quot;);</span>
<span class="fc" id="L51">        verify(observer, times(1)).onNext(&quot;twoResume&quot;);</span>
<span class="fc" id="L52">        verify(observer, times(1)).onNext(&quot;threeResume&quot;);</span>
<span class="fc" id="L53">        verify(observer, Mockito.never()).onError(any(Throwable.class));</span>
<span class="fc" id="L54">        verify(observer, times(1)).onComplete();</span>
<span class="fc" id="L55">        verifyNoMoreInteractions(observer);</span>
<span class="fc" id="L56">    }</span>

    @Test
    public void testResumeNextWithRuntimeException() {
        // Trigger failure on second element
<span class="fc" id="L61">        TestObservable f = new TestObservable(&quot;one&quot;, &quot;RUNTIMEEXCEPTION&quot;, &quot;two&quot;, &quot;three&quot;);</span>
<span class="fc" id="L62">        Observable&lt;String&gt; w = Observable.unsafeCreate(f);</span>
<span class="fc" id="L63">        Observable&lt;String&gt; resume = Observable.just(&quot;twoResume&quot;, &quot;threeResume&quot;);</span>
<span class="fc" id="L64">        Observable&lt;String&gt; observable = w.onExceptionResumeNext(resume);</span>

<span class="fc" id="L66">        Observer&lt;String&gt; observer = TestHelper.mockObserver();</span>
<span class="fc" id="L67">        observable.subscribe(observer);</span>

        try {
<span class="fc" id="L70">            f.t.join();</span>
<span class="nc" id="L71">        } catch (InterruptedException e) {</span>
<span class="nc" id="L72">            fail(e.getMessage());</span>
<span class="fc" id="L73">        }</span>

<span class="fc" id="L75">        verify(observer).onSubscribe((Disposable)any());</span>
<span class="fc" id="L76">        verify(observer, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L77">        verify(observer, Mockito.never()).onNext(&quot;two&quot;);</span>
<span class="fc" id="L78">        verify(observer, Mockito.never()).onNext(&quot;three&quot;);</span>
<span class="fc" id="L79">        verify(observer, times(1)).onNext(&quot;twoResume&quot;);</span>
<span class="fc" id="L80">        verify(observer, times(1)).onNext(&quot;threeResume&quot;);</span>
<span class="fc" id="L81">        verify(observer, Mockito.never()).onError(any(Throwable.class));</span>
<span class="fc" id="L82">        verify(observer, times(1)).onComplete();</span>
<span class="fc" id="L83">        verifyNoMoreInteractions(observer);</span>
<span class="fc" id="L84">    }</span>

    @Test
    public void testThrowablePassesThru() {
        // Trigger failure on second element
<span class="fc" id="L89">        TestObservable f = new TestObservable(&quot;one&quot;, &quot;THROWABLE&quot;, &quot;two&quot;, &quot;three&quot;);</span>
<span class="fc" id="L90">        Observable&lt;String&gt; w = Observable.unsafeCreate(f);</span>
<span class="fc" id="L91">        Observable&lt;String&gt; resume = Observable.just(&quot;twoResume&quot;, &quot;threeResume&quot;);</span>
<span class="fc" id="L92">        Observable&lt;String&gt; observable = w.onExceptionResumeNext(resume);</span>

<span class="fc" id="L94">        Observer&lt;String&gt; observer = TestHelper.mockObserver();</span>
<span class="fc" id="L95">        observable.subscribe(observer);</span>

        try {
<span class="fc" id="L98">            f.t.join();</span>
<span class="nc" id="L99">        } catch (InterruptedException e) {</span>
<span class="nc" id="L100">            fail(e.getMessage());</span>
<span class="fc" id="L101">        }</span>

<span class="fc" id="L103">        verify(observer).onSubscribe((Disposable)any());</span>
<span class="fc" id="L104">        verify(observer, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L105">        verify(observer, never()).onNext(&quot;two&quot;);</span>
<span class="fc" id="L106">        verify(observer, never()).onNext(&quot;three&quot;);</span>
<span class="fc" id="L107">        verify(observer, never()).onNext(&quot;twoResume&quot;);</span>
<span class="fc" id="L108">        verify(observer, never()).onNext(&quot;threeResume&quot;);</span>
<span class="fc" id="L109">        verify(observer, times(1)).onError(any(Throwable.class));</span>
<span class="fc" id="L110">        verify(observer, never()).onComplete();</span>
<span class="fc" id="L111">        verifyNoMoreInteractions(observer);</span>
<span class="fc" id="L112">    }</span>

    @Test
    public void testErrorPassesThru() {
        // Trigger failure on second element
<span class="fc" id="L117">        TestObservable f = new TestObservable(&quot;one&quot;, &quot;ERROR&quot;, &quot;two&quot;, &quot;three&quot;);</span>
<span class="fc" id="L118">        Observable&lt;String&gt; w = Observable.unsafeCreate(f);</span>
<span class="fc" id="L119">        Observable&lt;String&gt; resume = Observable.just(&quot;twoResume&quot;, &quot;threeResume&quot;);</span>
<span class="fc" id="L120">        Observable&lt;String&gt; observable = w.onExceptionResumeNext(resume);</span>

<span class="fc" id="L122">        Observer&lt;String&gt; observer = TestHelper.mockObserver();</span>
<span class="fc" id="L123">        observable.subscribe(observer);</span>

        try {
<span class="fc" id="L126">            f.t.join();</span>
<span class="nc" id="L127">        } catch (InterruptedException e) {</span>
<span class="nc" id="L128">            fail(e.getMessage());</span>
<span class="fc" id="L129">        }</span>

<span class="fc" id="L131">        verify(observer).onSubscribe((Disposable)any());</span>
<span class="fc" id="L132">        verify(observer, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L133">        verify(observer, never()).onNext(&quot;two&quot;);</span>
<span class="fc" id="L134">        verify(observer, never()).onNext(&quot;three&quot;);</span>
<span class="fc" id="L135">        verify(observer, never()).onNext(&quot;twoResume&quot;);</span>
<span class="fc" id="L136">        verify(observer, never()).onNext(&quot;threeResume&quot;);</span>
<span class="fc" id="L137">        verify(observer, times(1)).onError(any(Throwable.class));</span>
<span class="fc" id="L138">        verify(observer, never()).onComplete();</span>
<span class="fc" id="L139">        verifyNoMoreInteractions(observer);</span>
<span class="fc" id="L140">    }</span>

    @Test
    public void testMapResumeAsyncNext() {
        // Trigger multiple failures
<span class="fc" id="L145">        Observable&lt;String&gt; w = Observable.just(&quot;one&quot;, &quot;fail&quot;, &quot;two&quot;, &quot;three&quot;, &quot;fail&quot;);</span>
        // Resume Observable is async
<span class="fc" id="L147">        TestObservable f = new TestObservable(&quot;twoResume&quot;, &quot;threeResume&quot;);</span>
<span class="fc" id="L148">        Observable&lt;String&gt; resume = Observable.unsafeCreate(f);</span>

        // Introduce map function that fails intermittently (Map does not prevent this when the Observer is a
        //  rx.operator incl onErrorResumeNextViaObservable)
<span class="fc" id="L152">        w = w.map(new Function&lt;String, String&gt;() {</span>
            @Override
            public String apply(String s) {
<span class="fc bfc" id="L155" title="All 2 branches covered.">                if (&quot;fail&quot;.equals(s)) {</span>
<span class="fc" id="L156">                    throw new RuntimeException(&quot;Forced Failure&quot;);</span>
                }
<span class="fc" id="L158">                System.out.println(&quot;BadMapper:&quot; + s);</span>
<span class="fc" id="L159">                return s;</span>
            }
        });

<span class="fc" id="L163">        Observable&lt;String&gt; observable = w.onExceptionResumeNext(resume);</span>

<span class="fc" id="L165">        Observer&lt;String&gt; observer = TestHelper.mockObserver();</span>
<span class="fc" id="L166">        observable.subscribe(observer);</span>

        try {
            // if the thread gets started (which it shouldn't if it's working correctly)
<span class="pc bpc" id="L170" title="1 of 2 branches missed.">            if (f.t != null) {</span>
<span class="fc" id="L171">                f.t.join();</span>
            }
<span class="nc" id="L173">        } catch (InterruptedException e) {</span>
<span class="nc" id="L174">            fail(e.getMessage());</span>
<span class="fc" id="L175">        }</span>

<span class="fc" id="L177">        verify(observer, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L178">        verify(observer, never()).onNext(&quot;two&quot;);</span>
<span class="fc" id="L179">        verify(observer, never()).onNext(&quot;three&quot;);</span>
<span class="fc" id="L180">        verify(observer, times(1)).onNext(&quot;twoResume&quot;);</span>
<span class="fc" id="L181">        verify(observer, times(1)).onNext(&quot;threeResume&quot;);</span>
<span class="fc" id="L182">        verify(observer, Mockito.never()).onError(any(Throwable.class));</span>
<span class="fc" id="L183">        verify(observer, times(1)).onComplete();</span>
<span class="fc" id="L184">    }</span>

    @Test
    public void testBackpressure() {
<span class="fc" id="L188">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>
<span class="fc" id="L189">        Observable.range(0, 100000)</span>
<span class="fc" id="L190">                .onExceptionResumeNext(Observable.just(1))</span>
<span class="fc" id="L191">                .observeOn(Schedulers.computation())</span>
<span class="fc" id="L192">                .map(new Function&lt;Integer, Integer&gt;() {</span>
                    int c;

                    @Override
                    public Integer apply(Integer t1) {
<span class="fc bfc" id="L197" title="All 2 branches covered.">                        if (c++ &lt;= 1) {</span>
                            // slow
                            try {
<span class="fc" id="L200">                                Thread.sleep(500);</span>
<span class="nc" id="L201">                            } catch (InterruptedException e) {</span>
<span class="nc" id="L202">                                e.printStackTrace();</span>
<span class="fc" id="L203">                            }</span>
                        }
<span class="fc" id="L205">                        return t1;</span>
                    }

                })
<span class="fc" id="L209">                .subscribe(to);</span>
<span class="fc" id="L210">        to.awaitTerminalEvent();</span>
<span class="fc" id="L211">        to.assertNoErrors();</span>
<span class="fc" id="L212">    }</span>

    private static class TestObservable implements ObservableSource&lt;String&gt; {

        final String[] values;
        Thread t;

<span class="fc" id="L219">        TestObservable(String... values) {</span>
<span class="fc" id="L220">            this.values = values;</span>
<span class="fc" id="L221">        }</span>

        @Override
        public void subscribe(final Observer&lt;? super String&gt; observer) {
<span class="fc" id="L225">            observer.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L226">            System.out.println(&quot;TestObservable subscribed to ...&quot;);</span>
<span class="fc" id="L227">            t = new Thread(new Runnable() {</span>

                @Override
                public void run() {
                    try {
<span class="fc" id="L232">                        System.out.println(&quot;running TestObservable thread&quot;);</span>
<span class="fc bfc" id="L233" title="All 2 branches covered.">                        for (String s : values) {</span>
<span class="fc bfc" id="L234" title="All 2 branches covered.">                            if (&quot;EXCEPTION&quot;.equals(s)) {</span>
<span class="fc" id="L235">                                throw new Exception(&quot;Forced Exception&quot;);</span>
<span class="fc bfc" id="L236" title="All 2 branches covered.">                            } else if (&quot;RUNTIMEEXCEPTION&quot;.equals(s)) {</span>
<span class="fc" id="L237">                                throw new RuntimeException(&quot;Forced RuntimeException&quot;);</span>
<span class="fc bfc" id="L238" title="All 2 branches covered.">                            } else if (&quot;ERROR&quot;.equals(s)) {</span>
<span class="fc" id="L239">                                throw new Error(&quot;Forced Error&quot;);</span>
<span class="fc bfc" id="L240" title="All 2 branches covered.">                            } else if (&quot;THROWABLE&quot;.equals(s)) {</span>
<span class="fc" id="L241">                                throw new Throwable(&quot;Forced Throwable&quot;);</span>
                            }
<span class="fc" id="L243">                            System.out.println(&quot;TestObservable onNext: &quot; + s);</span>
<span class="fc" id="L244">                            observer.onNext(s);</span>
                        }
<span class="fc" id="L246">                        System.out.println(&quot;TestObservable onComplete&quot;);</span>
<span class="fc" id="L247">                        observer.onComplete();</span>
<span class="fc" id="L248">                    } catch (Throwable e) {</span>
<span class="fc" id="L249">                        System.out.println(&quot;TestObservable onError: &quot; + e);</span>
<span class="fc" id="L250">                        observer.onError(e);</span>
<span class="fc" id="L251">                    }</span>
<span class="fc" id="L252">                }</span>

            });
<span class="fc" id="L255">            System.out.println(&quot;starting TestObservable thread&quot;);</span>
<span class="fc" id="L256">            t.start();</span>
<span class="fc" id="L257">            System.out.println(&quot;done starting TestObservable thread&quot;);</span>
<span class="fc" id="L258">        }</span>
    }
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>