<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>ObservableRetryWithPredicateTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.internal.operators.observable</a> &gt; <span class="el_source">ObservableRetryWithPredicateTest.java</span></div><h1>ObservableRetryWithPredicateTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.internal.operators.observable;

import static org.junit.Assert.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.*;

import org.junit.Test;
import org.mockito.InOrder;

import io.reactivex.*;
import io.reactivex.Observable;
import io.reactivex.Observer;
import io.reactivex.disposables.*;
import io.reactivex.exceptions.*;
import io.reactivex.functions.*;
import io.reactivex.internal.functions.Functions;
import io.reactivex.observers.*;
import io.reactivex.subjects.PublishSubject;

<span class="fc" id="L38">public class ObservableRetryWithPredicateTest {</span>
<span class="fc" id="L39">    BiPredicate&lt;Integer, Throwable&gt; retryTwice = new BiPredicate&lt;Integer, Throwable&gt;() {</span>
        @Override
        public boolean test(Integer t1, Throwable t2) {
<span class="fc bfc" id="L42" title="All 2 branches covered.">            return t1 &lt;= 2;</span>
        }
    };
<span class="fc" id="L45">    BiPredicate&lt;Integer, Throwable&gt; retry5 = new BiPredicate&lt;Integer, Throwable&gt;() {</span>
        @Override
        public boolean test(Integer t1, Throwable t2) {
<span class="fc bfc" id="L48" title="All 2 branches covered.">            return t1 &lt;= 5;</span>
        }
    };
<span class="fc" id="L51">    BiPredicate&lt;Integer, Throwable&gt; retryOnTestException = new BiPredicate&lt;Integer, Throwable&gt;() {</span>
        @Override
        public boolean test(Integer t1, Throwable t2) {
<span class="fc" id="L54">            return t2 instanceof IOException;</span>
        }
    };
    @Test
    public void testWithNothingToRetry() {
<span class="fc" id="L59">        Observable&lt;Integer&gt; source = Observable.range(0, 3);</span>

<span class="fc" id="L61">        Observer&lt;Integer&gt; o = TestHelper.mockObserver();</span>
<span class="fc" id="L62">        InOrder inOrder = inOrder(o);</span>

<span class="fc" id="L64">        source.retry(retryTwice).subscribe(o);</span>

<span class="fc" id="L66">        inOrder.verify(o).onNext(0);</span>
<span class="fc" id="L67">        inOrder.verify(o).onNext(1);</span>
<span class="fc" id="L68">        inOrder.verify(o).onNext(2);</span>
<span class="fc" id="L69">        inOrder.verify(o).onComplete();</span>
<span class="fc" id="L70">        verify(o, never()).onError(any(Throwable.class));</span>
<span class="fc" id="L71">    }</span>

    @Test
    public void testRetryTwice() {
<span class="fc" id="L75">        Observable&lt;Integer&gt; source = Observable.unsafeCreate(new ObservableSource&lt;Integer&gt;() {</span>
            int count;
            @Override
            public void subscribe(Observer&lt;? super Integer&gt; t1) {
<span class="fc" id="L79">                t1.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L80">                count++;</span>
<span class="fc" id="L81">                t1.onNext(0);</span>
<span class="fc" id="L82">                t1.onNext(1);</span>
<span class="fc bfc" id="L83" title="All 2 branches covered.">                if (count == 1) {</span>
<span class="fc" id="L84">                    t1.onError(new TestException());</span>
<span class="fc" id="L85">                    return;</span>
                }
<span class="fc" id="L87">                t1.onNext(2);</span>
<span class="fc" id="L88">                t1.onNext(3);</span>
<span class="fc" id="L89">                t1.onComplete();</span>
<span class="fc" id="L90">            }</span>
        });

<span class="fc" id="L93">        Observer&lt;Integer&gt; o = TestHelper.mockObserver();</span>
<span class="fc" id="L94">        InOrder inOrder = inOrder(o);</span>

<span class="fc" id="L96">        source.retry(retryTwice).subscribe(o);</span>

<span class="fc" id="L98">        inOrder.verify(o).onNext(0);</span>
<span class="fc" id="L99">        inOrder.verify(o).onNext(1);</span>
<span class="fc" id="L100">        inOrder.verify(o).onNext(0);</span>
<span class="fc" id="L101">        inOrder.verify(o).onNext(1);</span>
<span class="fc" id="L102">        inOrder.verify(o).onNext(2);</span>
<span class="fc" id="L103">        inOrder.verify(o).onNext(3);</span>
<span class="fc" id="L104">        inOrder.verify(o).onComplete();</span>
<span class="fc" id="L105">        verify(o, never()).onError(any(Throwable.class));</span>

<span class="fc" id="L107">    }</span>

    @Test
    public void testRetryTwiceAndGiveUp() {
<span class="fc" id="L111">        Observable&lt;Integer&gt; source = Observable.unsafeCreate(new ObservableSource&lt;Integer&gt;() {</span>
            @Override
            public void subscribe(Observer&lt;? super Integer&gt; t1) {
<span class="fc" id="L114">                t1.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L115">                t1.onNext(0);</span>
<span class="fc" id="L116">                t1.onNext(1);</span>
<span class="fc" id="L117">                t1.onError(new TestException());</span>
<span class="fc" id="L118">            }</span>
        });

<span class="fc" id="L121">        Observer&lt;Integer&gt; o = TestHelper.mockObserver();</span>
<span class="fc" id="L122">        InOrder inOrder = inOrder(o);</span>

<span class="fc" id="L124">        source.retry(retryTwice).subscribe(o);</span>

<span class="fc" id="L126">        inOrder.verify(o).onNext(0);</span>
<span class="fc" id="L127">        inOrder.verify(o).onNext(1);</span>
<span class="fc" id="L128">        inOrder.verify(o).onNext(0);</span>
<span class="fc" id="L129">        inOrder.verify(o).onNext(1);</span>
<span class="fc" id="L130">        inOrder.verify(o).onNext(0);</span>
<span class="fc" id="L131">        inOrder.verify(o).onNext(1);</span>
<span class="fc" id="L132">        inOrder.verify(o).onError(any(TestException.class));</span>
<span class="fc" id="L133">        verify(o, never()).onComplete();</span>

<span class="fc" id="L135">    }</span>

    @Test
    public void testRetryOnSpecificException() {
<span class="fc" id="L139">        Observable&lt;Integer&gt; source = Observable.unsafeCreate(new ObservableSource&lt;Integer&gt;() {</span>
            int count;
            @Override
            public void subscribe(Observer&lt;? super Integer&gt; t1) {
<span class="fc" id="L143">                t1.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L144">                count++;</span>
<span class="fc" id="L145">                t1.onNext(0);</span>
<span class="fc" id="L146">                t1.onNext(1);</span>
<span class="fc bfc" id="L147" title="All 2 branches covered.">                if (count == 1) {</span>
<span class="fc" id="L148">                    t1.onError(new IOException());</span>
<span class="fc" id="L149">                    return;</span>
                }
<span class="fc" id="L151">                t1.onNext(2);</span>
<span class="fc" id="L152">                t1.onNext(3);</span>
<span class="fc" id="L153">                t1.onComplete();</span>
<span class="fc" id="L154">            }</span>
        });

<span class="fc" id="L157">        Observer&lt;Integer&gt; o = TestHelper.mockObserver();</span>
<span class="fc" id="L158">        InOrder inOrder = inOrder(o);</span>

<span class="fc" id="L160">        source.retry(retryOnTestException).subscribe(o);</span>

<span class="fc" id="L162">        inOrder.verify(o).onNext(0);</span>
<span class="fc" id="L163">        inOrder.verify(o).onNext(1);</span>
<span class="fc" id="L164">        inOrder.verify(o).onNext(0);</span>
<span class="fc" id="L165">        inOrder.verify(o).onNext(1);</span>
<span class="fc" id="L166">        inOrder.verify(o).onNext(2);</span>
<span class="fc" id="L167">        inOrder.verify(o).onNext(3);</span>
<span class="fc" id="L168">        inOrder.verify(o).onComplete();</span>
<span class="fc" id="L169">        verify(o, never()).onError(any(Throwable.class));</span>
<span class="fc" id="L170">    }</span>

    @Test
    public void testRetryOnSpecificExceptionAndNotOther() {
<span class="fc" id="L174">        final IOException ioe = new IOException();</span>
<span class="fc" id="L175">        final TestException te = new TestException();</span>
<span class="fc" id="L176">        Observable&lt;Integer&gt; source = Observable.unsafeCreate(new ObservableSource&lt;Integer&gt;() {</span>
            int count;
            @Override
            public void subscribe(Observer&lt;? super Integer&gt; t1) {
<span class="fc" id="L180">                t1.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L181">                count++;</span>
<span class="fc" id="L182">                t1.onNext(0);</span>
<span class="fc" id="L183">                t1.onNext(1);</span>
<span class="fc bfc" id="L184" title="All 2 branches covered.">                if (count == 1) {</span>
<span class="fc" id="L185">                    t1.onError(ioe);</span>
<span class="fc" id="L186">                    return;</span>
                }
<span class="fc" id="L188">                t1.onNext(2);</span>
<span class="fc" id="L189">                t1.onNext(3);</span>
<span class="fc" id="L190">                t1.onError(te);</span>
<span class="fc" id="L191">            }</span>
        });

<span class="fc" id="L194">        Observer&lt;Integer&gt; o = TestHelper.mockObserver();</span>
<span class="fc" id="L195">        InOrder inOrder = inOrder(o);</span>

<span class="fc" id="L197">        source.retry(retryOnTestException).subscribe(o);</span>

<span class="fc" id="L199">        inOrder.verify(o).onNext(0);</span>
<span class="fc" id="L200">        inOrder.verify(o).onNext(1);</span>
<span class="fc" id="L201">        inOrder.verify(o).onNext(0);</span>
<span class="fc" id="L202">        inOrder.verify(o).onNext(1);</span>
<span class="fc" id="L203">        inOrder.verify(o).onNext(2);</span>
<span class="fc" id="L204">        inOrder.verify(o).onNext(3);</span>
<span class="fc" id="L205">        inOrder.verify(o).onError(te);</span>
<span class="fc" id="L206">        verify(o, never()).onError(ioe);</span>
<span class="fc" id="L207">        verify(o, never()).onComplete();</span>
<span class="fc" id="L208">    }</span>

    @Test
    public void testUnsubscribeFromRetry() {
<span class="fc" id="L212">        PublishSubject&lt;Integer&gt; subject = PublishSubject.create();</span>
<span class="fc" id="L213">        final AtomicInteger count = new AtomicInteger(0);</span>
<span class="fc" id="L214">        Disposable sub = subject.retry(retryTwice).subscribe(new Consumer&lt;Integer&gt;() {</span>
            @Override
            public void accept(Integer n) {
<span class="fc" id="L217">                count.incrementAndGet();</span>
<span class="fc" id="L218">            }</span>
        });
<span class="fc" id="L220">        subject.onNext(1);</span>
<span class="fc" id="L221">        sub.dispose();</span>
<span class="fc" id="L222">        subject.onNext(2);</span>
<span class="fc" id="L223">        assertEquals(1, count.get());</span>
<span class="fc" id="L224">    }</span>

    @Test(timeout = 10000)
    public void testUnsubscribeAfterError() {

<span class="fc" id="L229">        Observer&lt;Long&gt; observer = TestHelper.mockObserver();</span>

        // Observable that always fails after 100ms
<span class="fc" id="L232">        ObservableRetryTest.SlowObservable so = new ObservableRetryTest.SlowObservable(100, 0, &quot;testUnsubscribeAfterError&quot;);</span>
<span class="fc" id="L233">        Observable&lt;Long&gt; o = Observable</span>
<span class="fc" id="L234">                .unsafeCreate(so)</span>
<span class="fc" id="L235">                .retry(retry5);</span>

<span class="fc" id="L237">        ObservableRetryTest.AsyncObserver&lt;Long&gt; async = new ObservableRetryTest.AsyncObserver&lt;Long&gt;(observer);</span>

<span class="fc" id="L239">        o.subscribe(async);</span>

<span class="fc" id="L241">        async.await();</span>

<span class="fc" id="L243">        InOrder inOrder = inOrder(observer);</span>
        // Should fail once
<span class="fc" id="L245">        inOrder.verify(observer, times(1)).onError(any(Throwable.class));</span>
<span class="fc" id="L246">        inOrder.verify(observer, never()).onComplete();</span>

<span class="fc" id="L248">        assertEquals(&quot;Start 6 threads, retry 5 then fail on 6&quot;, 6, so.efforts.get());</span>
<span class="fc" id="L249">        assertEquals(&quot;Only 1 active subscription&quot;, 1, so.maxActive.get());</span>
<span class="fc" id="L250">    }</span>

    @Test(timeout = 10000)
    public void testTimeoutWithRetry() {

<span class="fc" id="L255">        Observer&lt;Long&gt; observer = TestHelper.mockObserver();</span>

        // Observable that sends every 100ms (timeout fails instead)
<span class="fc" id="L258">        ObservableRetryTest.SlowObservable so = new ObservableRetryTest.SlowObservable(100, 10, &quot;testTimeoutWithRetry&quot;);</span>
<span class="fc" id="L259">        Observable&lt;Long&gt; o = Observable</span>
<span class="fc" id="L260">                .unsafeCreate(so)</span>
<span class="fc" id="L261">                .timeout(80, TimeUnit.MILLISECONDS)</span>
<span class="fc" id="L262">                .retry(retry5);</span>

<span class="fc" id="L264">        ObservableRetryTest.AsyncObserver&lt;Long&gt; async = new ObservableRetryTest.AsyncObserver&lt;Long&gt;(observer);</span>

<span class="fc" id="L266">        o.subscribe(async);</span>

<span class="fc" id="L268">        async.await();</span>

<span class="fc" id="L270">        InOrder inOrder = inOrder(observer);</span>
        // Should fail once
<span class="fc" id="L272">        inOrder.verify(observer, times(1)).onError(any(Throwable.class));</span>
<span class="fc" id="L273">        inOrder.verify(observer, never()).onComplete();</span>

<span class="fc" id="L275">        assertEquals(&quot;Start 6 threads, retry 5 then fail on 6&quot;, 6, so.efforts.get());</span>
<span class="fc" id="L276">    }</span>

    @Test
    public void testIssue2826() {
<span class="fc" id="L280">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>
<span class="fc" id="L281">        final RuntimeException e = new RuntimeException(&quot;You shall not pass&quot;);</span>
<span class="fc" id="L282">        final AtomicInteger c = new AtomicInteger();</span>
<span class="fc" id="L283">        Observable.just(1).map(new Function&lt;Integer, Integer&gt;() {</span>
            @Override
            public Integer apply(Integer t1) {
<span class="fc" id="L286">                c.incrementAndGet();</span>
<span class="fc" id="L287">                throw e;</span>
            }
<span class="fc" id="L289">        }).retry(retry5).subscribe(to);</span>

<span class="fc" id="L291">        to.assertTerminated();</span>
<span class="fc" id="L292">        assertEquals(6, c.get());</span>
<span class="fc" id="L293">        assertEquals(Collections.singletonList(e), to.errors());</span>
<span class="fc" id="L294">    }</span>

    @Test
    public void testJustAndRetry() throws Exception {
<span class="fc" id="L298">        final AtomicBoolean throwException = new AtomicBoolean(true);</span>
<span class="fc" id="L299">        int value = Observable.just(1).map(new Function&lt;Integer, Integer&gt;() {</span>
            @Override
            public Integer apply(Integer t1) {
<span class="fc bfc" id="L302" title="All 2 branches covered.">                if (throwException.compareAndSet(true, false)) {</span>
<span class="fc" id="L303">                    throw new TestException();</span>
                }
<span class="fc" id="L305">                return t1;</span>
            }
<span class="fc" id="L307">        }).retry(1).blockingSingle();</span>

<span class="fc" id="L309">        assertEquals(1, value);</span>
<span class="fc" id="L310">    }</span>

    @Test
    public void testIssue3008RetryWithPredicate() {
<span class="fc" id="L314">        final List&lt;Long&gt; list = new CopyOnWriteArrayList&lt;Long&gt;();</span>
<span class="fc" id="L315">        final AtomicBoolean isFirst = new AtomicBoolean(true);</span>
<span class="fc" id="L316">        Observable.&lt;Long&gt; just(1L, 2L, 3L).map(new Function&lt;Long, Long&gt;() {</span>
            @Override
            public Long apply(Long x) {
<span class="fc" id="L319">                System.out.println(&quot;map &quot; + x);</span>
<span class="fc bfc" id="L320" title="All 4 branches covered.">                if (x == 2 &amp;&amp; isFirst.getAndSet(false)) {</span>
<span class="fc" id="L321">                    throw new RuntimeException(&quot;retryable error&quot;);</span>
                }
<span class="fc" id="L323">                return x;</span>
            }})
<span class="fc" id="L325">        .retry(new BiPredicate&lt;Integer, Throwable&gt;() {</span>
            @Override
            public boolean test(Integer t1, Throwable t2) {
<span class="fc" id="L328">                return true;</span>
            }})
<span class="fc" id="L330">        .forEach(new Consumer&lt;Long&gt;() {</span>

            @Override
            public void accept(Long t) {
<span class="fc" id="L334">                System.out.println(t);</span>
<span class="fc" id="L335">                list.add(t);</span>
<span class="fc" id="L336">            }});</span>
<span class="fc" id="L337">        assertEquals(Arrays.asList(1L, 1L, 2L, 3L), list);</span>
<span class="fc" id="L338">    }</span>

    @Test
    public void testIssue3008RetryInfinite() {
<span class="fc" id="L342">        final List&lt;Long&gt; list = new CopyOnWriteArrayList&lt;Long&gt;();</span>
<span class="fc" id="L343">        final AtomicBoolean isFirst = new AtomicBoolean(true);</span>
<span class="fc" id="L344">        Observable.&lt;Long&gt; just(1L, 2L, 3L).map(new Function&lt;Long, Long&gt;() {</span>
            @Override
            public Long apply(Long x) {
<span class="fc" id="L347">                System.out.println(&quot;map &quot; + x);</span>
<span class="fc bfc" id="L348" title="All 4 branches covered.">                if (x == 2 &amp;&amp; isFirst.getAndSet(false)) {</span>
<span class="fc" id="L349">                    throw new RuntimeException(&quot;retryable error&quot;);</span>
                }
<span class="fc" id="L351">                return x;</span>
            }})
<span class="fc" id="L353">        .retry()</span>
<span class="fc" id="L354">        .forEach(new Consumer&lt;Long&gt;() {</span>

            @Override
            public void accept(Long t) {
<span class="fc" id="L358">                System.out.println(t);</span>
<span class="fc" id="L359">                list.add(t);</span>
<span class="fc" id="L360">            }});</span>
<span class="fc" id="L361">        assertEquals(Arrays.asList(1L, 1L, 2L, 3L), list);</span>
<span class="fc" id="L362">    }</span>

    @Test
    public void predicateThrows() {

<span class="fc" id="L367">        TestObserver&lt;Object&gt; to = Observable.error(new TestException(&quot;Outer&quot;))</span>
<span class="fc" id="L368">        .retry(new Predicate&lt;Throwable&gt;() {</span>
            @Override
            public boolean test(Throwable e) throws Exception {
<span class="fc" id="L371">                throw new TestException(&quot;Inner&quot;);</span>
            }
        })
<span class="fc" id="L374">        .test()</span>
<span class="fc" id="L375">        .assertFailure(CompositeException.class);</span>

<span class="fc" id="L377">        List&lt;Throwable&gt; errors = TestHelper.compositeList(to.errors().get(0));</span>

<span class="fc" id="L379">        TestHelper.assertError(errors, 0, TestException.class, &quot;Outer&quot;);</span>
<span class="fc" id="L380">        TestHelper.assertError(errors, 1, TestException.class, &quot;Inner&quot;);</span>
<span class="fc" id="L381">    }</span>

    @Test
    public void dontRetry() {
<span class="fc" id="L385">        Observable.error(new TestException(&quot;Outer&quot;))</span>
<span class="fc" id="L386">        .retry(Functions.alwaysFalse())</span>
<span class="fc" id="L387">        .test()</span>
<span class="fc" id="L388">        .assertFailureAndMessage(TestException.class, &quot;Outer&quot;);</span>
<span class="fc" id="L389">    }</span>

    @Test
    public void retryDisposeRace() {
<span class="fc bfc" id="L393" title="All 2 branches covered.">        for (int i = 0; i &lt; TestHelper.RACE_DEFAULT_LOOPS; i++) {</span>
<span class="fc" id="L394">            final PublishSubject&lt;Integer&gt; ps = PublishSubject.create();</span>

<span class="fc" id="L396">            final TestObserver&lt;Integer&gt; to = ps.retry(Functions.alwaysTrue()).test();</span>

<span class="fc" id="L398">            final TestException ex = new TestException();</span>

<span class="fc" id="L400">            Runnable r1 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L403">                    ps.onError(ex);</span>
<span class="fc" id="L404">                }</span>
            };

<span class="fc" id="L407">            Runnable r2 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L410">                    to.cancel();</span>
<span class="fc" id="L411">                }</span>
            };

<span class="fc" id="L414">            TestHelper.race(r1, r2);</span>

<span class="fc" id="L416">            to.assertEmpty();</span>
        }
<span class="fc" id="L418">    }</span>

    @Test
    public void bipredicateThrows() {

<span class="fc" id="L423">        TestObserver&lt;Object&gt; to = Observable.error(new TestException(&quot;Outer&quot;))</span>
<span class="fc" id="L424">        .retry(new BiPredicate&lt;Integer, Throwable&gt;() {</span>
            @Override
            public boolean test(Integer n, Throwable e) throws Exception {
<span class="fc" id="L427">                throw new TestException(&quot;Inner&quot;);</span>
            }
        })
<span class="fc" id="L430">        .test()</span>
<span class="fc" id="L431">        .assertFailure(CompositeException.class);</span>

<span class="fc" id="L433">        List&lt;Throwable&gt; errors = TestHelper.compositeList(to.errors().get(0));</span>

<span class="fc" id="L435">        TestHelper.assertError(errors, 0, TestException.class, &quot;Outer&quot;);</span>
<span class="fc" id="L436">        TestHelper.assertError(errors, 1, TestException.class, &quot;Inner&quot;);</span>
<span class="fc" id="L437">    }</span>

    @Test
    public void retryBiPredicateDisposeRace() {
<span class="fc bfc" id="L441" title="All 2 branches covered.">        for (int i = 0; i &lt; TestHelper.RACE_DEFAULT_LOOPS; i++) {</span>
<span class="fc" id="L442">            final PublishSubject&lt;Integer&gt; ps = PublishSubject.create();</span>

<span class="fc" id="L444">            final TestObserver&lt;Integer&gt; to = ps.retry(new BiPredicate&lt;Object, Object&gt;() {</span>
                @Override
                public boolean test(Object t1, Object t2) throws Exception {
<span class="fc" id="L447">                    return true;</span>
                }
<span class="fc" id="L449">            }).test();</span>

<span class="fc" id="L451">            final TestException ex = new TestException();</span>

<span class="fc" id="L453">            Runnable r1 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L456">                    ps.onError(ex);</span>
<span class="fc" id="L457">                }</span>
            };

<span class="fc" id="L460">            Runnable r2 = new Runnable() {</span>
                @Override
                public void run() {
<span class="fc" id="L463">                    to.cancel();</span>
<span class="fc" id="L464">                }</span>
            };

<span class="fc" id="L467">            TestHelper.race(r1, r2);</span>

<span class="fc" id="L469">            to.assertEmpty();</span>
        }
<span class="fc" id="L471">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>