<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>SafeObserverTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.observers</a> &gt; <span class="el_source">SafeObserverTest.java</span></div><h1>SafeObserverTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.observers;

import static org.junit.Assert.*;

import java.util.List;
import java.util.concurrent.atomic.AtomicReference;

import org.junit.*;

import io.reactivex.*;
import io.reactivex.disposables.*;
import io.reactivex.exceptions.*;
import io.reactivex.plugins.RxJavaPlugins;

<span class="fc" id="L28">public class SafeObserverTest {</span>

    @Test
    public void onNextFailure() {
<span class="fc" id="L32">        AtomicReference&lt;Throwable&gt; onError = new AtomicReference&lt;Throwable&gt;();</span>
        try {
<span class="nc" id="L34">            OBSERVER_ONNEXT_FAIL(onError).onNext(&quot;one&quot;);</span>
<span class="nc" id="L35">            fail(&quot;expects exception to be thrown&quot;);</span>
<span class="fc" id="L36">        } catch (Exception e) {</span>
<span class="fc" id="L37">            assertNull(onError.get());</span>
<span class="fc" id="L38">            assertTrue(e instanceof SafeObserverTestException);</span>
<span class="fc" id="L39">            assertEquals(&quot;onNextFail&quot;, e.getMessage());</span>
<span class="nc" id="L40">        }</span>
<span class="fc" id="L41">    }</span>

    @Test
    public void onNextFailureSafe() {
<span class="fc" id="L45">        AtomicReference&lt;Throwable&gt; onError = new AtomicReference&lt;Throwable&gt;();</span>
        try {
<span class="fc" id="L47">            SafeObserver&lt;String&gt; safeObserver = new SafeObserver&lt;String&gt;(OBSERVER_ONNEXT_FAIL(onError));</span>
<span class="fc" id="L48">            safeObserver.onSubscribe(Disposables.empty());</span>
<span class="fc" id="L49">            safeObserver.onNext(&quot;one&quot;);</span>
<span class="fc" id="L50">            assertNotNull(onError.get());</span>
<span class="fc" id="L51">            assertTrue(onError.get() instanceof SafeObserverTestException);</span>
<span class="fc" id="L52">            assertEquals(&quot;onNextFail&quot;, onError.get().getMessage());</span>
<span class="nc" id="L53">        } catch (Exception e) {</span>
<span class="nc" id="L54">            fail(&quot;expects exception to be passed to onError&quot;);</span>
<span class="fc" id="L55">        }</span>
<span class="fc" id="L56">    }</span>

    @Test
    public void onCompleteFailure() {
<span class="fc" id="L60">        AtomicReference&lt;Throwable&gt; onError = new AtomicReference&lt;Throwable&gt;();</span>
        try {
<span class="nc" id="L62">            OBSERVER_ONCOMPLETED_FAIL(onError).onComplete();</span>
<span class="nc" id="L63">            fail(&quot;expects exception to be thrown&quot;);</span>
<span class="fc" id="L64">        } catch (Exception e) {</span>
<span class="fc" id="L65">            assertNull(onError.get());</span>
<span class="fc" id="L66">            assertTrue(e instanceof SafeObserverTestException);</span>
<span class="fc" id="L67">            assertEquals(&quot;onCompleteFail&quot;, e.getMessage());</span>
<span class="nc" id="L68">        }</span>
<span class="fc" id="L69">    }</span>

    @Test
    public void onErrorFailure() {
        try {
<span class="nc" id="L74">            OBSERVER_ONERROR_FAIL().onError(new SafeObserverTestException(&quot;error!&quot;));</span>
<span class="nc" id="L75">            fail(&quot;expects exception to be thrown&quot;);</span>
<span class="fc" id="L76">        } catch (Exception e) {</span>
<span class="fc" id="L77">            assertTrue(e instanceof SafeObserverTestException);</span>
<span class="fc" id="L78">            assertEquals(&quot;onErrorFail&quot;, e.getMessage());</span>
<span class="nc" id="L79">        }</span>
<span class="fc" id="L80">    }</span>

    @Test
    @Ignore(&quot;Observers can't throw&quot;)
    public void onErrorFailureSafe() {
        try {
<span class="nc" id="L86">            new SafeObserver&lt;String&gt;(OBSERVER_ONERROR_FAIL()).onError(new SafeObserverTestException(&quot;error!&quot;));</span>
<span class="nc" id="L87">            fail(&quot;expects exception to be thrown&quot;);</span>
<span class="nc" id="L88">        } catch (Exception e) {</span>
<span class="nc" id="L89">            e.printStackTrace();</span>
<span class="nc" id="L90">            assertTrue(e instanceof RuntimeException);</span>
<span class="nc" id="L91">            assertEquals(&quot;Error occurred when trying to propagate error to Observer.onError&quot;, e.getMessage());</span>

<span class="nc" id="L93">            Throwable e2 = e.getCause();</span>
<span class="nc" id="L94">            assertTrue(e2 instanceof CompositeException);</span>
<span class="nc" id="L95">            List&lt;Throwable&gt; innerExceptions = ((CompositeException) e2).getExceptions();</span>
<span class="nc" id="L96">            assertEquals(2, innerExceptions.size());</span>

<span class="nc" id="L98">            Throwable e3 = innerExceptions.get(0);</span>
<span class="nc" id="L99">            assertTrue(e3 instanceof SafeObserverTestException);</span>
<span class="nc" id="L100">            assertEquals(&quot;error!&quot;, e3.getMessage());</span>

<span class="nc" id="L102">            Throwable e4 = innerExceptions.get(1);</span>
<span class="nc" id="L103">            assertTrue(e4 instanceof SafeObserverTestException);</span>
<span class="nc" id="L104">            assertEquals(&quot;onErrorFail&quot;, e4.getMessage());</span>
<span class="nc" id="L105">        }</span>
<span class="nc" id="L106">    }</span>

    @Test
    @Ignore(&quot;Observers can't throw&quot;)
    public void onErrorNotImplementedFailureSafe() {
        try {
<span class="nc" id="L112">            new SafeObserver&lt;String&gt;(OBSERVER_ONERROR_NOTIMPLEMENTED()).onError(new SafeObserverTestException(&quot;error!&quot;));</span>
<span class="nc" id="L113">            fail(&quot;expects exception to be thrown&quot;);</span>
<span class="nc" id="L114">        } catch (Exception e) {</span>
//            assertTrue(e instanceof OnErrorNotImplementedException);
<span class="nc" id="L116">            assertTrue(e.getCause() instanceof SafeObserverTestException);</span>
<span class="nc" id="L117">            assertEquals(&quot;error!&quot;, e.getCause().getMessage());</span>
<span class="nc" id="L118">        }</span>
<span class="nc" id="L119">    }</span>

    @Test
    public void onNextOnErrorFailure() {
        try {
<span class="nc" id="L124">            OBSERVER_ONNEXT_ONERROR_FAIL().onNext(&quot;one&quot;);</span>
<span class="nc" id="L125">            fail(&quot;expects exception to be thrown&quot;);</span>
<span class="fc" id="L126">        } catch (Exception e) {</span>
<span class="fc" id="L127">            e.printStackTrace();</span>
<span class="fc" id="L128">            assertTrue(e instanceof SafeObserverTestException);</span>
<span class="fc" id="L129">            assertEquals(&quot;onNextFail&quot;, e.getMessage());</span>
<span class="nc" id="L130">        }</span>
<span class="fc" id="L131">    }</span>

    @Test
    @Ignore(&quot;Observers can't throw&quot;)
    public void onNextOnErrorFailureSafe() {
        try {
<span class="nc" id="L137">            new SafeObserver&lt;String&gt;(OBSERVER_ONNEXT_ONERROR_FAIL()).onNext(&quot;one&quot;);</span>
<span class="nc" id="L138">            fail(&quot;expects exception to be thrown&quot;);</span>
<span class="nc" id="L139">        } catch (Exception e) {</span>
<span class="nc" id="L140">            e.printStackTrace();</span>
<span class="nc" id="L141">            assertTrue(e instanceof RuntimeException);</span>
<span class="nc" id="L142">            assertEquals(&quot;Error occurred when trying to propagate error to Observer.onError&quot;, e.getMessage());</span>

<span class="nc" id="L144">            Throwable e2 = e.getCause();</span>
<span class="nc" id="L145">            assertTrue(e2 instanceof CompositeException);</span>
<span class="nc" id="L146">            List&lt;Throwable&gt; innerExceptions = ((CompositeException) e2).getExceptions();</span>
<span class="nc" id="L147">            assertEquals(2, innerExceptions.size());</span>

<span class="nc" id="L149">            Throwable e3 = innerExceptions.get(0);</span>
<span class="nc" id="L150">            assertTrue(e3 instanceof SafeObserverTestException);</span>
<span class="nc" id="L151">            assertEquals(&quot;onNextFail&quot;, e3.getMessage());</span>

<span class="nc" id="L153">            Throwable e4 = innerExceptions.get(1);</span>
<span class="nc" id="L154">            assertTrue(e4 instanceof SafeObserverTestException);</span>
<span class="nc" id="L155">            assertEquals(&quot;onErrorFail&quot;, e4.getMessage());</span>
<span class="nc" id="L156">        }</span>
<span class="nc" id="L157">    }</span>

<span class="fc" id="L159">    static final Disposable THROWING_DISPOSABLE = new Disposable() {</span>

        @Override
        public boolean isDisposed() {
            // TODO Auto-generated method stub
<span class="nc" id="L164">            return false;</span>
        }

        @Override
        public void dispose() {
            // break contract by throwing exception
<span class="nc" id="L170">            throw new SafeObserverTestException(&quot;failure from unsubscribe&quot;);</span>
        }
    };

    @Test
    @Ignore(&quot;Observers can't throw&quot;)
    public void onCompleteSuccessWithUnsubscribeFailure() {
<span class="nc" id="L177">        Observer&lt;String&gt; o = OBSERVER_SUCCESS();</span>
        try {
<span class="nc" id="L179">            o.onSubscribe(THROWING_DISPOSABLE);</span>
<span class="nc" id="L180">            new SafeObserver&lt;String&gt;(o).onComplete();</span>
<span class="nc" id="L181">            fail(&quot;expects exception to be thrown&quot;);</span>
<span class="nc" id="L182">        } catch (Exception e) {</span>
<span class="nc" id="L183">            e.printStackTrace();</span>

            // FIXME no longer assertable
//            assertTrue(o.isUnsubscribed());
//            assertTrue(e instanceof UnsubscribeFailedException);
<span class="nc" id="L188">            assertTrue(e.getCause() instanceof SafeObserverTestException);</span>
<span class="nc" id="L189">            assertEquals(&quot;failure from unsubscribe&quot;, e.getMessage());</span>
            // expected since onError fails so SafeObserver can't help
<span class="nc" id="L191">        }</span>
<span class="nc" id="L192">    }</span>

    @Test
    @Ignore(&quot;Observers can't throw&quot;)
    public void onErrorSuccessWithUnsubscribeFailure() {
<span class="nc" id="L197">        AtomicReference&lt;Throwable&gt; onError = new AtomicReference&lt;Throwable&gt;();</span>
<span class="nc" id="L198">        Observer&lt;String&gt; o = OBSERVER_SUCCESS(onError);</span>
        try {
<span class="nc" id="L200">            o.onSubscribe(THROWING_DISPOSABLE);</span>
<span class="nc" id="L201">            new SafeObserver&lt;String&gt;(o).onError(new SafeObserverTestException(&quot;failed&quot;));</span>
<span class="nc" id="L202">            fail(&quot;we expect the unsubscribe failure to cause an exception to be thrown&quot;);</span>
<span class="nc" id="L203">        } catch (Exception e) {</span>
<span class="nc" id="L204">            e.printStackTrace();</span>

            // FIXME no longer assertable
//            assertTrue(o.isUnsubscribed());

            // we still expect onError to have received something before unsubscribe blew up
<span class="nc" id="L210">            assertNotNull(onError.get());</span>
<span class="nc" id="L211">            assertTrue(onError.get() instanceof SafeObserverTestException);</span>
<span class="nc" id="L212">            assertEquals(&quot;failed&quot;, onError.get().getMessage());</span>

            // now assert the exception that was thrown
<span class="nc" id="L215">            RuntimeException onErrorFailedException = (RuntimeException) e;</span>
<span class="nc" id="L216">            assertTrue(onErrorFailedException.getCause() instanceof SafeObserverTestException);</span>
<span class="nc" id="L217">            assertEquals(&quot;failure from unsubscribe&quot;, e.getMessage());</span>
<span class="nc" id="L218">        }</span>
<span class="nc" id="L219">    }</span>

    @Test
    @Ignore(&quot;Observers can't throw&quot;)
    public void onErrorFailureWithUnsubscribeFailure() {
<span class="nc" id="L224">        Observer&lt;String&gt; o = OBSERVER_ONERROR_FAIL();</span>
        try {
<span class="nc" id="L226">            o.onSubscribe(THROWING_DISPOSABLE);</span>
<span class="nc" id="L227">            new SafeObserver&lt;String&gt;(o).onError(new SafeObserverTestException(&quot;onError failure&quot;));</span>
<span class="nc" id="L228">            fail(&quot;expects exception to be thrown&quot;);</span>
<span class="nc" id="L229">        } catch (Exception e) {</span>
<span class="nc" id="L230">            e.printStackTrace();</span>

            // FIXME no longer assertable
//            assertTrue(o.isUnsubscribed());

            // assertions for what is expected for the actual failure propagated to onError which then fails
<span class="nc" id="L236">            assertTrue(e instanceof RuntimeException);</span>
<span class="nc" id="L237">            assertEquals(&quot;Error occurred when trying to propagate error to Observer.onError and during unsubscription.&quot;, e.getMessage());</span>

<span class="nc" id="L239">            Throwable e2 = e.getCause();</span>
<span class="nc" id="L240">            assertTrue(e2 instanceof CompositeException);</span>
<span class="nc" id="L241">            List&lt;Throwable&gt; innerExceptions = ((CompositeException) e2).getExceptions();</span>
<span class="nc" id="L242">            assertEquals(3, innerExceptions.size());</span>

<span class="nc" id="L244">            Throwable e3 = innerExceptions.get(0);</span>
<span class="nc" id="L245">            assertTrue(e3 instanceof SafeObserverTestException);</span>
<span class="nc" id="L246">            assertEquals(&quot;onError failure&quot;, e3.getMessage());</span>

<span class="nc" id="L248">            Throwable e4 = innerExceptions.get(1);</span>
<span class="nc" id="L249">            assertTrue(e4 instanceof SafeObserverTestException);</span>
<span class="nc" id="L250">            assertEquals(&quot;onErrorFail&quot;, e4.getMessage());</span>

<span class="nc" id="L252">            Throwable e5 = innerExceptions.get(2);</span>
<span class="nc" id="L253">            assertTrue(e5 instanceof SafeObserverTestException);</span>
<span class="nc" id="L254">            assertEquals(&quot;failure from unsubscribe&quot;, e5.getMessage());</span>
<span class="nc" id="L255">        }</span>
<span class="nc" id="L256">    }</span>

    @Test
    @Ignore(&quot;Observers can't throw&quot;)
    public void onErrorNotImplementedFailureWithUnsubscribeFailure() {
<span class="nc" id="L261">        Observer&lt;String&gt; o = OBSERVER_ONERROR_NOTIMPLEMENTED();</span>
        try {
<span class="nc" id="L263">            o.onSubscribe(THROWING_DISPOSABLE);</span>
<span class="nc" id="L264">            new SafeObserver&lt;String&gt;(o).onError(new SafeObserverTestException(&quot;error!&quot;));</span>
<span class="nc" id="L265">            fail(&quot;expects exception to be thrown&quot;);</span>
<span class="nc" id="L266">        } catch (Exception e) {</span>
<span class="nc" id="L267">            e.printStackTrace();</span>

            // FIXME no longer assertable
//            assertTrue(o.isUnsubscribed());

            // assertions for what is expected for the actual failure propagated to onError which then fails
<span class="nc" id="L273">            assertTrue(e instanceof RuntimeException);</span>
<span class="nc" id="L274">            assertEquals(&quot;Observer.onError not implemented and error while unsubscribing.&quot;, e.getMessage());</span>

<span class="nc" id="L276">            Throwable e2 = e.getCause();</span>
<span class="nc" id="L277">            assertTrue(e2 instanceof CompositeException);</span>
<span class="nc" id="L278">            List&lt;Throwable&gt; innerExceptions = ((CompositeException) e2).getExceptions();</span>
<span class="nc" id="L279">            assertEquals(2, innerExceptions.size());</span>

<span class="nc" id="L281">            Throwable e3 = innerExceptions.get(0);</span>
<span class="nc" id="L282">            assertTrue(e3 instanceof SafeObserverTestException);</span>
<span class="nc" id="L283">            assertEquals(&quot;error!&quot;, e3.getMessage());</span>

<span class="nc" id="L285">            Throwable e4 = innerExceptions.get(1);</span>
<span class="nc" id="L286">            assertTrue(e4 instanceof SafeObserverTestException);</span>
<span class="nc" id="L287">            assertEquals(&quot;failure from unsubscribe&quot;, e4.getMessage());</span>
<span class="nc" id="L288">        }</span>
<span class="nc" id="L289">    }</span>

    private static Observer&lt;String&gt; OBSERVER_SUCCESS() {
<span class="nc" id="L292">        return new DefaultObserver&lt;String&gt;() {</span>

            @Override
            public void onComplete() {

<span class="nc" id="L297">            }</span>

            @Override
            public void onError(Throwable e) {

<span class="nc" id="L302">            }</span>

            @Override
            public void onNext(String args) {

<span class="nc" id="L307">            }</span>
        };

    }

    private static Observer&lt;String&gt; OBSERVER_SUCCESS(final AtomicReference&lt;Throwable&gt; onError) {
<span class="nc" id="L313">        return new DefaultObserver&lt;String&gt;() {</span>

            @Override
            public void onComplete() {

<span class="nc" id="L318">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="nc" id="L322">                onError.set(e);</span>
<span class="nc" id="L323">            }</span>

            @Override
            public void onNext(String args) {

<span class="nc" id="L328">            }</span>
        };

    }

    private static Observer&lt;String&gt; OBSERVER_ONNEXT_FAIL(final AtomicReference&lt;Throwable&gt; onError) {
<span class="fc" id="L334">        return new DefaultObserver&lt;String&gt;() {</span>

            @Override
            public void onComplete() {

<span class="nc" id="L339">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="fc" id="L343">                onError.set(e);</span>
<span class="fc" id="L344">            }</span>

            @Override
            public void onNext(String args) {
<span class="fc" id="L348">                throw new SafeObserverTestException(&quot;onNextFail&quot;);</span>
            }
        };

    }

    private static Observer&lt;String&gt; OBSERVER_ONNEXT_ONERROR_FAIL() {
<span class="fc" id="L355">        return new DefaultObserver&lt;String&gt;() {</span>

            @Override
            public void onComplete() {

<span class="nc" id="L360">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="nc" id="L364">                throw new SafeObserverTestException(&quot;onErrorFail&quot;);</span>
            }

            @Override
            public void onNext(String args) {
<span class="fc" id="L369">                throw new SafeObserverTestException(&quot;onNextFail&quot;);</span>
            }

        };
    }

    private static Observer&lt;String&gt; OBSERVER_ONERROR_FAIL() {
<span class="fc" id="L376">        return new DefaultObserver&lt;String&gt;() {</span>

            @Override
            public void onComplete() {

<span class="nc" id="L381">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="fc" id="L385">                throw new SafeObserverTestException(&quot;onErrorFail&quot;);</span>
            }

            @Override
            public void onNext(String args) {

<span class="nc" id="L391">            }</span>

        };
    }

    private static Observer&lt;String&gt; OBSERVER_ONERROR_NOTIMPLEMENTED() {
<span class="nc" id="L397">        return new DefaultObserver&lt;String&gt;() {</span>

            @Override
            public void onComplete() {

<span class="nc" id="L402">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="nc" id="L406">                throw new RuntimeException(e);</span>
//                throw new OnErrorNotImplementedException(e);
            }

            @Override
            public void onNext(String args) {

<span class="nc" id="L413">            }</span>

        };
    }

    private static Observer&lt;String&gt; OBSERVER_ONCOMPLETED_FAIL(final AtomicReference&lt;Throwable&gt; onError) {
<span class="fc" id="L419">        return new DefaultObserver&lt;String&gt;() {</span>

            @Override
            public void onComplete() {
<span class="fc" id="L423">                throw new SafeObserverTestException(&quot;onCompleteFail&quot;);</span>
            }

            @Override
            public void onError(Throwable e) {
<span class="nc" id="L428">                onError.set(e);</span>
<span class="nc" id="L429">            }</span>

            @Override
            public void onNext(String args) {

<span class="nc" id="L434">            }</span>

        };
    }

    @SuppressWarnings(&quot;serial&quot;)
    static class SafeObserverTestException extends RuntimeException {
        SafeObserverTestException(String message) {
<span class="fc" id="L442">            super(message);</span>
<span class="fc" id="L443">        }</span>
    }

    @Test
    @Ignore(&quot;Observers can't throw&quot;)
    public void testOnCompletedThrows() {
<span class="nc" id="L449">        final AtomicReference&lt;Throwable&gt; error = new AtomicReference&lt;Throwable&gt;();</span>
<span class="nc" id="L450">        SafeObserver&lt;Integer&gt; observer = new SafeObserver&lt;Integer&gt;(new DefaultObserver&lt;Integer&gt;() {</span>
            @Override
            public void onNext(Integer t) {

<span class="nc" id="L454">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="nc" id="L458">                error.set(e);</span>
<span class="nc" id="L459">            }</span>

            @Override
            public void onComplete() {
<span class="nc" id="L463">                throw new TestException();</span>
            }
        });

        try {
<span class="nc" id="L468">            observer.onComplete();</span>
<span class="nc" id="L469">            Assert.fail();</span>
<span class="nc" id="L470">        } catch (RuntimeException e) {</span>
<span class="nc" id="L471">           assertNull(error.get());</span>
<span class="nc" id="L472">        }</span>
<span class="nc" id="L473">    }</span>

    @Test
    public void testActual() {
<span class="fc" id="L477">        Observer&lt;Integer&gt; actual = new DefaultObserver&lt;Integer&gt;() {</span>
            @Override
            public void onNext(Integer t) {
<span class="nc" id="L480">            }</span>

            @Override
            public void onError(Throwable e) {
<span class="nc" id="L484">            }</span>

            @Override
            public void onComplete() {
<span class="nc" id="L488">            }</span>
        };
<span class="fc" id="L490">        SafeObserver&lt;Integer&gt; observer = new SafeObserver&lt;Integer&gt;(actual);</span>

<span class="fc" id="L492">        assertSame(actual, observer.downstream);</span>
<span class="fc" id="L493">    }</span>

    @Test
    public void dispose() {
<span class="fc" id="L497">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

<span class="fc" id="L499">        SafeObserver&lt;Integer&gt; so = new SafeObserver&lt;Integer&gt;(to);</span>

<span class="fc" id="L501">        Disposable d = Disposables.empty();</span>

<span class="fc" id="L503">        so.onSubscribe(d);</span>

<span class="fc" id="L505">        to.dispose();</span>

<span class="fc" id="L507">        assertTrue(d.isDisposed());</span>

<span class="fc" id="L509">        assertTrue(so.isDisposed());</span>
<span class="fc" id="L510">    }</span>

    @Test
    public void onNextAfterComplete() {
<span class="fc" id="L514">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

<span class="fc" id="L516">        SafeObserver&lt;Integer&gt; so = new SafeObserver&lt;Integer&gt;(to);</span>

<span class="fc" id="L518">        Disposable d = Disposables.empty();</span>

<span class="fc" id="L520">        so.onSubscribe(d);</span>

<span class="fc" id="L522">        so.onComplete();</span>

<span class="fc" id="L524">        so.onNext(1);</span>

<span class="fc" id="L526">        so.onError(new TestException());</span>

<span class="fc" id="L528">        so.onComplete();</span>

<span class="fc" id="L530">        to.assertResult();</span>
<span class="fc" id="L531">    }</span>

    @Test
    public void onNextNull() {
<span class="fc" id="L535">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

<span class="fc" id="L537">        SafeObserver&lt;Integer&gt; so = new SafeObserver&lt;Integer&gt;(to);</span>

<span class="fc" id="L539">        Disposable d = Disposables.empty();</span>

<span class="fc" id="L541">        so.onSubscribe(d);</span>

<span class="fc" id="L543">        so.onNext(null);</span>

<span class="fc" id="L545">        to.assertFailure(NullPointerException.class);</span>
<span class="fc" id="L546">    }</span>

    @Test
    public void onNextWithoutOnSubscribe() {
<span class="fc" id="L550">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

<span class="fc" id="L552">        SafeObserver&lt;Integer&gt; so = new SafeObserver&lt;Integer&gt;(to);</span>

<span class="fc" id="L554">        so.onNext(1);</span>

<span class="fc" id="L556">        to.assertFailureAndMessage(NullPointerException.class, &quot;Subscription not set!&quot;);</span>
<span class="fc" id="L557">    }</span>

    @Test
    public void onErrorWithoutOnSubscribe() {
<span class="fc" id="L561">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

<span class="fc" id="L563">        SafeObserver&lt;Integer&gt; so = new SafeObserver&lt;Integer&gt;(to);</span>

<span class="fc" id="L565">        so.onError(new TestException());</span>

<span class="fc" id="L567">        to.assertFailure(CompositeException.class);</span>

<span class="fc" id="L569">        TestHelper.assertError(to, 0, TestException.class);</span>
<span class="fc" id="L570">        TestHelper.assertError(to, 1, NullPointerException.class, &quot;Subscription not set!&quot;);</span>
<span class="fc" id="L571">    }</span>

    @Test
    public void onCompleteWithoutOnSubscribe() {
<span class="fc" id="L575">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

<span class="fc" id="L577">        SafeObserver&lt;Integer&gt; so = new SafeObserver&lt;Integer&gt;(to);</span>

<span class="fc" id="L579">        so.onComplete();</span>

<span class="fc" id="L581">        to.assertFailureAndMessage(NullPointerException.class, &quot;Subscription not set!&quot;);</span>
<span class="fc" id="L582">    }</span>

    @Test
    public void onNextNormal() {
<span class="fc" id="L586">        TestObserver&lt;Integer&gt; to = new TestObserver&lt;Integer&gt;();</span>

<span class="fc" id="L588">        SafeObserver&lt;Integer&gt; so = new SafeObserver&lt;Integer&gt;(to);</span>

<span class="fc" id="L590">        Disposable d = Disposables.empty();</span>

<span class="fc" id="L592">        so.onSubscribe(d);</span>

<span class="fc" id="L594">        so.onNext(1);</span>
<span class="fc" id="L595">        so.onComplete();</span>

<span class="fc" id="L597">        to.assertResult(1);</span>
<span class="fc" id="L598">    }</span>

    static final class CrashDummy implements Observer&lt;Object&gt;, Disposable {
        boolean crashOnSubscribe;
        int crashOnNext;
        boolean crashOnError;
        boolean crashOnComplete;

        boolean crashDispose;

        Throwable error;

        CrashDummy(boolean crashOnSubscribe, int crashOnNext,
<span class="fc" id="L611">                boolean crashOnError, boolean crashOnComplete, boolean crashDispose) {</span>
<span class="fc" id="L612">            this.crashOnSubscribe = crashOnSubscribe;</span>
<span class="fc" id="L613">            this.crashOnNext = crashOnNext;</span>
<span class="fc" id="L614">            this.crashOnError = crashOnError;</span>
<span class="fc" id="L615">            this.crashOnComplete = crashOnComplete;</span>
<span class="fc" id="L616">            this.crashDispose = crashDispose;</span>
<span class="fc" id="L617">        }</span>

        @Override
        public void dispose() {
<span class="fc bfc" id="L621" title="All 2 branches covered.">            if (crashDispose) {</span>
<span class="fc" id="L622">                throw new TestException(&quot;dispose()&quot;);</span>
            }
<span class="fc" id="L624">        }</span>

        @Override
        public boolean isDisposed() {
<span class="nc" id="L628">            return false;</span>
        }

        @Override
        public void onSubscribe(Disposable d) {
<span class="fc bfc" id="L633" title="All 2 branches covered.">            if (crashOnSubscribe) {</span>
<span class="fc" id="L634">                throw new TestException(&quot;onSubscribe()&quot;);</span>
            }
<span class="fc" id="L636">        }</span>

        @Override
        public void onNext(Object value) {
<span class="pc bpc" id="L640" title="1 of 2 branches missed.">            if (--crashOnNext == 0) {</span>
<span class="fc" id="L641">                throw new TestException(&quot;onNext(&quot; + value + &quot;)&quot;);</span>
            }
<span class="nc" id="L643">        }</span>

        @Override
        public void onError(Throwable e) {
<span class="fc bfc" id="L647" title="All 2 branches covered.">            if (crashOnError) {</span>
<span class="fc" id="L648">                throw new TestException(&quot;onError(&quot; + e + &quot;)&quot;);</span>
            }
<span class="fc" id="L650">            error = e;</span>
<span class="fc" id="L651">        }</span>

        @Override
        public void onComplete() {
<span class="pc bpc" id="L655" title="1 of 2 branches missed.">            if (crashOnComplete) {</span>
<span class="fc" id="L656">                throw new TestException(&quot;onComplete()&quot;);</span>
            }
<span class="nc" id="L658">        }</span>

        public SafeObserver&lt;Object&gt; toSafe() {
<span class="fc" id="L661">            return new SafeObserver&lt;Object&gt;(this);</span>
        }

        public CrashDummy assertError(Class&lt;? extends Throwable&gt; clazz) {
<span class="pc bpc" id="L665" title="1 of 2 branches missed.">            if (!clazz.isInstance(error)) {</span>
<span class="nc" id="L666">                throw new AssertionError(&quot;Different error: &quot; + error);</span>
            }
<span class="fc" id="L668">            return this;</span>
        }

        public CrashDummy assertInnerError(int index, Class&lt;? extends Throwable&gt; clazz) {
<span class="fc" id="L672">            List&lt;Throwable&gt; cel = TestHelper.compositeList(error);</span>
<span class="fc" id="L673">            TestHelper.assertError(cel, index, clazz);</span>
<span class="fc" id="L674">            return this;</span>
        }

        public CrashDummy assertInnerError(int index, Class&lt;? extends Throwable&gt; clazz, String message) {
<span class="fc" id="L678">            List&lt;Throwable&gt; cel = TestHelper.compositeList(error);</span>
<span class="fc" id="L679">            TestHelper.assertError(cel, index, clazz, message);</span>
<span class="fc" id="L680">            return this;</span>
        }

    }

    @Test
    public void onNextOnErrorCrash() {
<span class="fc" id="L687">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L690">            CrashDummy cd = new CrashDummy(false, 1, true, false, false);</span>
<span class="fc" id="L691">            SafeObserver&lt;Object&gt; so = cd.toSafe();</span>
<span class="fc" id="L692">            so.onSubscribe(cd);</span>

<span class="fc" id="L694">            so.onNext(1);</span>

<span class="fc" id="L696">            TestHelper.assertError(list, 0, CompositeException.class);</span>
<span class="fc" id="L697">            List&lt;Throwable&gt; ce = TestHelper.compositeList(list.get(0));</span>
<span class="fc" id="L698">            TestHelper.assertError(ce, 0, TestException.class, &quot;onNext(1)&quot;);</span>
<span class="fc" id="L699">            TestHelper.assertError(ce, 1, TestException.class, &quot;onError(io.reactivex.exceptions.TestException: onNext(1))&quot;);</span>
        } finally {
<span class="fc" id="L701">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L703">    }</span>

    @Test
    public void onNextDisposeCrash() {
<span class="fc" id="L707">        CrashDummy cd = new CrashDummy(false, 1, false, false, true);</span>
<span class="fc" id="L708">        SafeObserver&lt;Object&gt; so = cd.toSafe();</span>
<span class="fc" id="L709">        so.onSubscribe(cd);</span>

<span class="fc" id="L711">        so.onNext(1);</span>

<span class="fc" id="L713">        cd.assertError(CompositeException.class);</span>
<span class="fc" id="L714">        cd.assertInnerError(0, TestException.class, &quot;onNext(1)&quot;);</span>
<span class="fc" id="L715">        cd.assertInnerError(1, TestException.class, &quot;dispose()&quot;);</span>
<span class="fc" id="L716">    }</span>

    @Test
    public void onSubscribeTwice() {
<span class="fc" id="L720">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L723">            CrashDummy cd = new CrashDummy(false, 1, false, false, false);</span>
<span class="fc" id="L724">            SafeObserver&lt;Object&gt; so = cd.toSafe();</span>
<span class="fc" id="L725">            so.onSubscribe(cd);</span>
<span class="fc" id="L726">            so.onSubscribe(cd);</span>

<span class="fc" id="L728">            TestHelper.assertError(list, 0, IllegalStateException.class);</span>
        } finally {
<span class="fc" id="L730">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L732">    }</span>

    @Test
    public void onSubscribeCrashes() {
<span class="fc" id="L736">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L739">            CrashDummy cd = new CrashDummy(true, 1, false, false, false);</span>
<span class="fc" id="L740">            SafeObserver&lt;Object&gt; so = cd.toSafe();</span>
<span class="fc" id="L741">            so.onSubscribe(cd);</span>

<span class="fc" id="L743">            TestHelper.assertUndeliverable(list, 0, TestException.class, &quot;onSubscribe()&quot;);</span>
        } finally {
<span class="fc" id="L745">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L747">    }</span>

    @Test
    public void onSubscribeAndDisposeCrashes() {
<span class="fc" id="L751">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L754">            CrashDummy cd = new CrashDummy(true, 1, false, false, true);</span>
<span class="fc" id="L755">            SafeObserver&lt;Object&gt; so = cd.toSafe();</span>
<span class="fc" id="L756">            so.onSubscribe(cd);</span>

<span class="fc" id="L758">            TestHelper.assertError(list, 0, CompositeException.class);</span>
<span class="fc" id="L759">            List&lt;Throwable&gt; ce = TestHelper.compositeList(list.get(0));</span>
<span class="fc" id="L760">            TestHelper.assertError(ce, 0, TestException.class, &quot;onSubscribe()&quot;);</span>
<span class="fc" id="L761">            TestHelper.assertError(ce, 1, TestException.class, &quot;dispose()&quot;);</span>
        } finally {
<span class="fc" id="L763">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L765">    }</span>

    @Test
    public void onNextOnSubscribeCrash() {
<span class="fc" id="L769">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L772">            CrashDummy cd = new CrashDummy(true, 1, false, false, false);</span>
<span class="fc" id="L773">            SafeObserver&lt;Object&gt; so = cd.toSafe();</span>

<span class="fc" id="L775">            so.onNext(1);</span>

<span class="fc" id="L777">            TestHelper.assertError(list, 0, CompositeException.class);</span>
<span class="fc" id="L778">            List&lt;Throwable&gt; ce = TestHelper.compositeList(list.get(0));</span>
<span class="fc" id="L779">            TestHelper.assertError(ce, 0, NullPointerException.class, &quot;Subscription not set!&quot;);</span>
<span class="fc" id="L780">            TestHelper.assertError(ce, 1, TestException.class, &quot;onSubscribe()&quot;);</span>
        } finally {
<span class="fc" id="L782">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L784">    }</span>

    @Test
    public void onNextNullDisposeCrashes() {
<span class="fc" id="L788">        CrashDummy cd = new CrashDummy(false, 1, false, false, true);</span>
<span class="fc" id="L789">        SafeObserver&lt;Object&gt; so = cd.toSafe();</span>
<span class="fc" id="L790">        so.onSubscribe(cd);</span>

<span class="fc" id="L792">        so.onNext(null);</span>

<span class="fc" id="L794">        cd.assertInnerError(0, NullPointerException.class);</span>
<span class="fc" id="L795">        cd.assertInnerError(1, TestException.class, &quot;dispose()&quot;);</span>
<span class="fc" id="L796">    }</span>

    @Test
    public void noSubscribeOnErrorCrashes() {
<span class="fc" id="L800">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L803">            CrashDummy cd = new CrashDummy(false, 1, true, false, false);</span>
<span class="fc" id="L804">            SafeObserver&lt;Object&gt; so = cd.toSafe();</span>

<span class="fc" id="L806">            so.onNext(1);</span>

<span class="fc" id="L808">            TestHelper.assertError(list, 0, CompositeException.class);</span>
<span class="fc" id="L809">            List&lt;Throwable&gt; ce = TestHelper.compositeList(list.get(0));</span>
<span class="fc" id="L810">            TestHelper.assertError(ce, 0, NullPointerException.class, &quot;Subscription not set!&quot;);</span>
<span class="fc" id="L811">            TestHelper.assertError(ce, 1, TestException.class, &quot;onError(java.lang.NullPointerException: Subscription not set!)&quot;);</span>
        } finally {
<span class="fc" id="L813">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L815">    }</span>

    @Test
    public void onErrorNull() {
<span class="fc" id="L819">        CrashDummy cd = new CrashDummy(false, 1, false, false, false);</span>
<span class="fc" id="L820">        SafeObserver&lt;Object&gt; so = cd.toSafe();</span>
<span class="fc" id="L821">        so.onSubscribe(cd);</span>

<span class="fc" id="L823">        so.onError(null);</span>

<span class="fc" id="L825">        cd.assertError(NullPointerException.class);</span>
<span class="fc" id="L826">    }</span>

    @Test
    public void onErrorNoSubscribeCrash() {
<span class="fc" id="L830">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L833">            CrashDummy cd = new CrashDummy(true, 1, false, false, false);</span>
<span class="fc" id="L834">            SafeObserver&lt;Object&gt; so = cd.toSafe();</span>

<span class="fc" id="L836">            so.onError(new TestException());</span>

<span class="fc" id="L838">            TestHelper.assertError(list, 0, CompositeException.class);</span>
<span class="fc" id="L839">            List&lt;Throwable&gt; ce = TestHelper.compositeList(list.get(0));</span>
<span class="fc" id="L840">            TestHelper.assertError(ce, 0, TestException.class);</span>
<span class="fc" id="L841">            TestHelper.assertError(ce, 1, NullPointerException.class, &quot;Subscription not set!&quot;);</span>
        } finally {
<span class="fc" id="L843">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L845">    }</span>

    @Test
    public void onErrorNoSubscribeOnErrorCrash() {
<span class="fc" id="L849">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L852">            CrashDummy cd = new CrashDummy(false, 1, true, false, false);</span>
<span class="fc" id="L853">            SafeObserver&lt;Object&gt; so = cd.toSafe();</span>

<span class="fc" id="L855">            so.onError(new TestException());</span>

<span class="fc" id="L857">            TestHelper.assertError(list, 0, CompositeException.class);</span>
<span class="fc" id="L858">            List&lt;Throwable&gt; ce = TestHelper.compositeList(list.get(0));</span>
<span class="fc" id="L859">            TestHelper.assertError(ce, 0, TestException.class);</span>
<span class="fc" id="L860">            TestHelper.assertError(ce, 1, NullPointerException.class, &quot;Subscription not set!&quot;);</span>
<span class="fc" id="L861">            TestHelper.assertError(ce, 2, TestException.class);</span>
        } finally {
<span class="fc" id="L863">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L865">    }</span>

    @Test
    public void onCompleteteCrash() {
<span class="fc" id="L869">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L872">            CrashDummy cd = new CrashDummy(false, 1, false, true, false);</span>
<span class="fc" id="L873">            SafeObserver&lt;Object&gt; so = cd.toSafe();</span>

<span class="fc" id="L875">            so.onSubscribe(cd);</span>

<span class="fc" id="L877">            so.onComplete();</span>

<span class="fc" id="L879">            TestHelper.assertUndeliverable(list, 0, TestException.class, &quot;onComplete()&quot;);</span>
        } finally {
<span class="fc" id="L881">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L883">    }</span>

    @Test
    public void onCompleteteNoSubscribeCrash() {
<span class="fc" id="L887">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L890">            CrashDummy cd = new CrashDummy(true, 1, false, true, false);</span>
<span class="fc" id="L891">            SafeObserver&lt;Object&gt; so = cd.toSafe();</span>

<span class="fc" id="L893">            so.onComplete();</span>

<span class="fc" id="L895">            TestHelper.assertError(list, 0, CompositeException.class);</span>
<span class="fc" id="L896">            List&lt;Throwable&gt; ce = TestHelper.compositeList(list.get(0));</span>
<span class="fc" id="L897">            TestHelper.assertError(ce, 0, NullPointerException.class, &quot;Subscription not set!&quot;);</span>
<span class="fc" id="L898">            TestHelper.assertError(ce, 1, TestException.class, &quot;onSubscribe()&quot;);</span>
        } finally {
<span class="fc" id="L900">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L902">    }</span>

    @Test
    public void onCompleteteNoSubscribeOnErrorCrash() {
<span class="fc" id="L906">        List&lt;Throwable&gt; list = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L909">            CrashDummy cd = new CrashDummy(false, 1, true, true, false);</span>
<span class="fc" id="L910">            SafeObserver&lt;Object&gt; so = cd.toSafe();</span>

<span class="fc" id="L912">            so.onComplete();</span>

<span class="fc" id="L914">            TestHelper.assertError(list, 0, CompositeException.class);</span>
<span class="fc" id="L915">            List&lt;Throwable&gt; ce = TestHelper.compositeList(list.get(0));</span>
<span class="fc" id="L916">            TestHelper.assertError(ce, 0, NullPointerException.class, &quot;Subscription not set!&quot;);</span>
<span class="fc" id="L917">            TestHelper.assertError(ce, 1, TestException.class);</span>
        } finally {
<span class="fc" id="L919">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L921">    }</span>

}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>