<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>LambdaObserverTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.internal.observers</a> &gt; <span class="el_source">LambdaObserverTest.java</span></div><h1>LambdaObserverTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.internal.observers;

import static org.junit.Assert.*;

import java.io.IOException;
import java.util.*;

import io.reactivex.internal.functions.Functions;
import org.junit.Test;

import io.reactivex.Observable;
import io.reactivex.Observer;
import io.reactivex.TestHelper;
import io.reactivex.disposables.*;
import io.reactivex.exceptions.*;
import io.reactivex.functions.*;
import io.reactivex.plugins.RxJavaPlugins;
import io.reactivex.subjects.PublishSubject;

<span class="fc" id="L33">public class LambdaObserverTest {</span>

    @Test
    public void onSubscribeThrows() {
<span class="fc" id="L37">        final List&lt;Object&gt; received = new ArrayList&lt;Object&gt;();</span>

<span class="fc" id="L39">        LambdaObserver&lt;Object&gt; o = new LambdaObserver&lt;Object&gt;(new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object v) throws Exception {
<span class="nc" id="L42">                received.add(v);</span>
<span class="nc" id="L43">            }</span>
        },
<span class="fc" id="L45">        new Consumer&lt;Throwable&gt;() {</span>
            @Override
            public void accept(Throwable e) throws Exception {
<span class="fc" id="L48">                received.add(e);</span>
<span class="fc" id="L49">            }</span>
<span class="fc" id="L50">        }, new Action() {</span>
            @Override
            public void run() throws Exception {
<span class="nc" id="L53">                received.add(100);</span>
<span class="nc" id="L54">            }</span>
<span class="fc" id="L55">        }, new Consumer&lt;Disposable&gt;() {</span>
            @Override
            public void accept(Disposable d) throws Exception {
<span class="fc" id="L58">                throw new TestException();</span>
            }
        });

<span class="fc" id="L62">        assertFalse(o.isDisposed());</span>

<span class="fc" id="L64">        Observable.just(1).subscribe(o);</span>

<span class="fc" id="L66">        assertTrue(received.toString(), received.get(0) instanceof TestException);</span>
<span class="fc" id="L67">        assertEquals(received.toString(), 1, received.size());</span>

<span class="fc" id="L69">        assertTrue(o.isDisposed());</span>
<span class="fc" id="L70">    }</span>

    @Test
    public void onNextThrows() {
<span class="fc" id="L74">        final List&lt;Object&gt; received = new ArrayList&lt;Object&gt;();</span>

<span class="fc" id="L76">        LambdaObserver&lt;Object&gt; o = new LambdaObserver&lt;Object&gt;(new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object v) throws Exception {
<span class="fc" id="L79">                throw new TestException();</span>
            }
        },
<span class="fc" id="L82">        new Consumer&lt;Throwable&gt;() {</span>
            @Override
            public void accept(Throwable e) throws Exception {
<span class="fc" id="L85">                received.add(e);</span>
<span class="fc" id="L86">            }</span>
<span class="fc" id="L87">        }, new Action() {</span>
            @Override
            public void run() throws Exception {
<span class="nc" id="L90">                received.add(100);</span>
<span class="nc" id="L91">            }</span>
<span class="fc" id="L92">        }, new Consumer&lt;Disposable&gt;() {</span>
            @Override
            public void accept(Disposable d) throws Exception {
<span class="fc" id="L95">            }</span>
        });

<span class="fc" id="L98">        assertFalse(o.isDisposed());</span>

<span class="fc" id="L100">        Observable.just(1).subscribe(o);</span>

<span class="fc" id="L102">        assertTrue(received.toString(), received.get(0) instanceof TestException);</span>
<span class="fc" id="L103">        assertEquals(received.toString(), 1, received.size());</span>

<span class="fc" id="L105">        assertTrue(o.isDisposed());</span>
<span class="fc" id="L106">    }</span>

    @Test
    public void onErrorThrows() {
<span class="fc" id="L110">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L113">            final List&lt;Object&gt; received = new ArrayList&lt;Object&gt;();</span>

<span class="fc" id="L115">            LambdaObserver&lt;Object&gt; o = new LambdaObserver&lt;Object&gt;(new Consumer&lt;Object&gt;() {</span>
                @Override
                public void accept(Object v) throws Exception {
<span class="nc" id="L118">                    received.add(v);</span>
<span class="nc" id="L119">                }</span>
            },
<span class="fc" id="L121">            new Consumer&lt;Throwable&gt;() {</span>
                @Override
                public void accept(Throwable e) throws Exception {
<span class="fc" id="L124">                    throw new TestException(&quot;Inner&quot;);</span>
                }
<span class="fc" id="L126">            }, new Action() {</span>
                @Override
                public void run() throws Exception {
<span class="nc" id="L129">                    received.add(100);</span>
<span class="nc" id="L130">                }</span>
<span class="fc" id="L131">            }, new Consumer&lt;Disposable&gt;() {</span>
                @Override
                public void accept(Disposable d) throws Exception {
<span class="fc" id="L134">                }</span>
            });

<span class="fc" id="L137">            assertFalse(o.isDisposed());</span>

<span class="fc" id="L139">            Observable.&lt;Integer&gt;error(new TestException(&quot;Outer&quot;)).subscribe(o);</span>

<span class="fc" id="L141">            assertTrue(received.toString(), received.isEmpty());</span>

<span class="fc" id="L143">            assertTrue(o.isDisposed());</span>

<span class="fc" id="L145">            TestHelper.assertError(errors, 0, CompositeException.class);</span>
<span class="fc" id="L146">            List&lt;Throwable&gt; ce = TestHelper.compositeList(errors.get(0));</span>
<span class="fc" id="L147">            TestHelper.assertError(ce, 0, TestException.class, &quot;Outer&quot;);</span>
<span class="fc" id="L148">            TestHelper.assertError(ce, 1, TestException.class, &quot;Inner&quot;);</span>
        } finally {
<span class="fc" id="L150">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L152">    }</span>

    @Test
    public void onCompleteThrows() {
<span class="fc" id="L156">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L159">            final List&lt;Object&gt; received = new ArrayList&lt;Object&gt;();</span>

<span class="fc" id="L161">            LambdaObserver&lt;Object&gt; o = new LambdaObserver&lt;Object&gt;(new Consumer&lt;Object&gt;() {</span>
                @Override
                public void accept(Object v) throws Exception {
<span class="nc" id="L164">                    received.add(v);</span>
<span class="nc" id="L165">                }</span>
            },
<span class="fc" id="L167">            new Consumer&lt;Throwable&gt;() {</span>
                @Override
                public void accept(Throwable e) throws Exception {
<span class="nc" id="L170">                    received.add(e);</span>
<span class="nc" id="L171">                }</span>
<span class="fc" id="L172">            }, new Action() {</span>
                @Override
                public void run() throws Exception {
<span class="fc" id="L175">                    throw new TestException();</span>
                }
<span class="fc" id="L177">            }, new Consumer&lt;Disposable&gt;() {</span>
                @Override
                public void accept(Disposable d) throws Exception {
<span class="fc" id="L180">                }</span>
            });

<span class="fc" id="L183">            assertFalse(o.isDisposed());</span>

<span class="fc" id="L185">            Observable.&lt;Integer&gt;empty().subscribe(o);</span>

<span class="fc" id="L187">            assertTrue(received.toString(), received.isEmpty());</span>

<span class="fc" id="L189">            assertTrue(o.isDisposed());</span>

<span class="fc" id="L191">            TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L193">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L195">    }</span>

    @Test
    public void badSourceOnSubscribe() {
<span class="fc" id="L199">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L201">            Observable&lt;Integer&gt; source = new Observable&lt;Integer&gt;() {</span>
                @Override
                public void subscribeActual(Observer&lt;? super Integer&gt; observer) {
<span class="fc" id="L204">                    Disposable d1 = Disposables.empty();</span>
<span class="fc" id="L205">                    observer.onSubscribe(d1);</span>
<span class="fc" id="L206">                    Disposable d2 = Disposables.empty();</span>
<span class="fc" id="L207">                    observer.onSubscribe(d2);</span>

<span class="fc" id="L209">                    assertFalse(d1.isDisposed());</span>
<span class="fc" id="L210">                    assertTrue(d2.isDisposed());</span>

<span class="fc" id="L212">                    observer.onNext(1);</span>
<span class="fc" id="L213">                    observer.onComplete();</span>
<span class="fc" id="L214">                }</span>
            };

<span class="fc" id="L217">            final List&lt;Object&gt; received = new ArrayList&lt;Object&gt;();</span>

<span class="fc" id="L219">            LambdaObserver&lt;Object&gt; o = new LambdaObserver&lt;Object&gt;(new Consumer&lt;Object&gt;() {</span>
                @Override
                public void accept(Object v) throws Exception {
<span class="fc" id="L222">                    received.add(v);</span>
<span class="fc" id="L223">                }</span>
            },
<span class="fc" id="L225">            new Consumer&lt;Throwable&gt;() {</span>
                @Override
                public void accept(Throwable e) throws Exception {
<span class="nc" id="L228">                    received.add(e);</span>
<span class="nc" id="L229">                }</span>
<span class="fc" id="L230">            }, new Action() {</span>
                @Override
                public void run() throws Exception {
<span class="fc" id="L233">                    received.add(100);</span>
<span class="fc" id="L234">                }</span>
<span class="fc" id="L235">            }, new Consumer&lt;Disposable&gt;() {</span>
                @Override
                public void accept(Disposable d) throws Exception {
<span class="fc" id="L238">                }</span>
            });

<span class="fc" id="L241">            source.subscribe(o);</span>

<span class="fc" id="L243">            assertEquals(Arrays.asList(1, 100), received);</span>

<span class="fc" id="L245">            TestHelper.assertError(errors, 0, ProtocolViolationException.class);</span>
        } finally {
<span class="fc" id="L247">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L249">    }</span>

    @Test
    public void badSourceEmitAfterDone() {
<span class="fc" id="L253">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L255">            Observable&lt;Integer&gt; source = new Observable&lt;Integer&gt;() {</span>
                @Override
                public void subscribeActual(Observer&lt;? super Integer&gt; observer) {
<span class="fc" id="L258">                    observer.onSubscribe(Disposables.empty());</span>

<span class="fc" id="L260">                    observer.onNext(1);</span>
<span class="fc" id="L261">                    observer.onComplete();</span>
<span class="fc" id="L262">                    observer.onNext(2);</span>
<span class="fc" id="L263">                    observer.onError(new TestException());</span>
<span class="fc" id="L264">                    observer.onComplete();</span>
<span class="fc" id="L265">                }</span>
            };

<span class="fc" id="L268">            final List&lt;Object&gt; received = new ArrayList&lt;Object&gt;();</span>

<span class="fc" id="L270">            LambdaObserver&lt;Object&gt; o = new LambdaObserver&lt;Object&gt;(new Consumer&lt;Object&gt;() {</span>
                @Override
                public void accept(Object v) throws Exception {
<span class="fc" id="L273">                    received.add(v);</span>
<span class="fc" id="L274">                }</span>
            },
<span class="fc" id="L276">            new Consumer&lt;Throwable&gt;() {</span>
                @Override
                public void accept(Throwable e) throws Exception {
<span class="nc" id="L279">                    received.add(e);</span>
<span class="nc" id="L280">                }</span>
<span class="fc" id="L281">            }, new Action() {</span>
                @Override
                public void run() throws Exception {
<span class="fc" id="L284">                    received.add(100);</span>
<span class="fc" id="L285">                }</span>
<span class="fc" id="L286">            }, new Consumer&lt;Disposable&gt;() {</span>
                @Override
                public void accept(Disposable d) throws Exception {
<span class="fc" id="L289">                }</span>
            });

<span class="fc" id="L292">            source.subscribe(o);</span>

<span class="fc" id="L294">            assertEquals(Arrays.asList(1, 100), received);</span>

<span class="fc" id="L296">            TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L298">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L300">    }</span>

    @Test
    public void onNextThrowsCancelsUpstream() {
<span class="fc" id="L304">        PublishSubject&lt;Integer&gt; ps = PublishSubject.create();</span>

<span class="fc" id="L306">        final List&lt;Throwable&gt; errors = new ArrayList&lt;Throwable&gt;();</span>

<span class="fc" id="L308">        ps.subscribe(new Consumer&lt;Integer&gt;() {</span>
            @Override
            public void accept(Integer v) throws Exception {
<span class="fc" id="L311">                throw new TestException();</span>
            }
<span class="fc" id="L313">        }, new Consumer&lt;Throwable&gt;() {</span>
            @Override
            public void accept(Throwable e) throws Exception {
<span class="fc" id="L316">                errors.add(e);</span>
<span class="fc" id="L317">            }</span>
        });

<span class="fc" id="L320">        assertTrue(&quot;No observers?!&quot;, ps.hasObservers());</span>
<span class="fc" id="L321">        assertTrue(&quot;Has errors already?!&quot;, errors.isEmpty());</span>

<span class="fc" id="L323">        ps.onNext(1);</span>

<span class="fc" id="L325">        assertFalse(&quot;Has observers?!&quot;, ps.hasObservers());</span>
<span class="fc" id="L326">        assertFalse(&quot;No errors?!&quot;, errors.isEmpty());</span>

<span class="fc" id="L328">        assertTrue(errors.toString(), errors.get(0) instanceof TestException);</span>
<span class="fc" id="L329">    }</span>

    @Test
    public void onSubscribeThrowsCancelsUpstream() {
<span class="fc" id="L333">        PublishSubject&lt;Integer&gt; ps = PublishSubject.create();</span>

<span class="fc" id="L335">        final List&lt;Throwable&gt; errors = new ArrayList&lt;Throwable&gt;();</span>

<span class="fc" id="L337">        ps.subscribe(new Consumer&lt;Integer&gt;() {</span>
            @Override
            public void accept(Integer v) throws Exception {
<span class="nc" id="L340">            }</span>
<span class="fc" id="L341">        }, new Consumer&lt;Throwable&gt;() {</span>
            @Override
            public void accept(Throwable e) throws Exception {
<span class="fc" id="L344">                errors.add(e);</span>
<span class="fc" id="L345">            }</span>
<span class="fc" id="L346">        }, new Action() {</span>
            @Override
            public void run() throws Exception {
<span class="nc" id="L349">            }</span>
<span class="fc" id="L350">        }, new Consumer&lt;Disposable&gt;() {</span>
            @Override
            public void accept(Disposable d) throws Exception {
<span class="fc" id="L353">                throw new TestException();</span>
            }
        });

<span class="fc" id="L357">        assertFalse(&quot;Has observers?!&quot;, ps.hasObservers());</span>
<span class="fc" id="L358">        assertFalse(&quot;No errors?!&quot;, errors.isEmpty());</span>

<span class="fc" id="L360">        assertTrue(errors.toString(), errors.get(0) instanceof TestException);</span>
<span class="fc" id="L361">    }</span>

    @Test
    public void onErrorMissingShouldReportNoCustomOnError() {
<span class="fc" id="L365">        LambdaObserver&lt;Integer&gt; o = new LambdaObserver&lt;Integer&gt;(Functions.&lt;Integer&gt;emptyConsumer(),</span>
                Functions.ON_ERROR_MISSING,
                Functions.EMPTY_ACTION,
<span class="fc" id="L368">                Functions.&lt;Disposable&gt;emptyConsumer());</span>

<span class="fc" id="L370">        assertFalse(o.hasCustomOnError());</span>
<span class="fc" id="L371">    }</span>

    @Test
    public void customOnErrorShouldReportCustomOnError() {
<span class="fc" id="L375">        LambdaObserver&lt;Integer&gt; o = new LambdaObserver&lt;Integer&gt;(Functions.&lt;Integer&gt;emptyConsumer(),</span>
<span class="fc" id="L376">                Functions.&lt;Throwable&gt;emptyConsumer(),</span>
                Functions.EMPTY_ACTION,
<span class="fc" id="L378">                Functions.&lt;Disposable&gt;emptyConsumer());</span>

<span class="fc" id="L380">        assertTrue(o.hasCustomOnError());</span>
<span class="fc" id="L381">    }</span>

    @Test
    public void disposedObserverShouldReportErrorOnGlobalErrorHandler() {
<span class="fc" id="L385">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L387">            final List&lt;Throwable&gt; observerErrors = Collections.synchronizedList(new ArrayList&lt;Throwable&gt;());</span>

<span class="fc" id="L389">            LambdaObserver&lt;Integer&gt; o = new LambdaObserver&lt;Integer&gt;(Functions.&lt;Integer&gt;emptyConsumer(),</span>
<span class="fc" id="L390">                    new Consumer&lt;Throwable&gt;() {</span>
                        @Override
                        public void accept(Throwable t) {
<span class="nc" id="L393">                            observerErrors.add(t);</span>
<span class="nc" id="L394">                        }</span>
                    },
                    Functions.EMPTY_ACTION,
<span class="fc" id="L397">                    Functions.&lt;Disposable&gt;emptyConsumer());</span>

<span class="fc" id="L399">            o.dispose();</span>
<span class="fc" id="L400">            o.onError(new IOException());</span>
<span class="fc" id="L401">            o.onError(new IOException());</span>

<span class="fc" id="L403">            assertTrue(observerErrors.isEmpty());</span>
<span class="fc" id="L404">            TestHelper.assertUndeliverable(errors, 0, IOException.class);</span>
<span class="fc" id="L405">            TestHelper.assertUndeliverable(errors, 1, IOException.class);</span>
        } finally {
<span class="fc" id="L407">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L409">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>