<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>FlowableOnExceptionResumeNextViaFlowableTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.internal.operators.flowable</a> &gt; <span class="el_source">FlowableOnExceptionResumeNextViaFlowableTest.java</span></div><h1>FlowableOnExceptionResumeNextViaFlowableTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.internal.operators.flowable;

import static org.junit.Assert.fail;
import static org.mockito.Mockito.*;

import org.junit.Test;
import org.mockito.Mockito;
import org.reactivestreams.*;

import io.reactivex.*;
import io.reactivex.exceptions.TestException;
import io.reactivex.functions.Function;
import io.reactivex.internal.subscriptions.BooleanSubscription;
import io.reactivex.processors.PublishProcessor;
import io.reactivex.schedulers.Schedulers;
import io.reactivex.subscribers.TestSubscriber;

<span class="fc" id="L31">public class FlowableOnExceptionResumeNextViaFlowableTest {</span>

    @Test
    public void testResumeNextWithException() {
        // Trigger failure on second element
<span class="fc" id="L36">        TestObservable f = new TestObservable(&quot;one&quot;, &quot;EXCEPTION&quot;, &quot;two&quot;, &quot;three&quot;);</span>
<span class="fc" id="L37">        Flowable&lt;String&gt; w = Flowable.unsafeCreate(f);</span>
<span class="fc" id="L38">        Flowable&lt;String&gt; resume = Flowable.just(&quot;twoResume&quot;, &quot;threeResume&quot;);</span>
<span class="fc" id="L39">        Flowable&lt;String&gt; flowable = w.onExceptionResumeNext(resume);</span>

<span class="fc" id="L41">        Subscriber&lt;String&gt; subscriber = TestHelper.mockSubscriber();</span>
<span class="fc" id="L42">        flowable.subscribe(subscriber);</span>

        try {
<span class="fc" id="L45">            f.t.join();</span>
<span class="nc" id="L46">        } catch (InterruptedException e) {</span>
<span class="nc" id="L47">            fail(e.getMessage());</span>
<span class="fc" id="L48">        }</span>

<span class="fc" id="L50">        verify(subscriber).onSubscribe((Subscription)any());</span>
<span class="fc" id="L51">        verify(subscriber, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L52">        verify(subscriber, Mockito.never()).onNext(&quot;two&quot;);</span>
<span class="fc" id="L53">        verify(subscriber, Mockito.never()).onNext(&quot;three&quot;);</span>
<span class="fc" id="L54">        verify(subscriber, times(1)).onNext(&quot;twoResume&quot;);</span>
<span class="fc" id="L55">        verify(subscriber, times(1)).onNext(&quot;threeResume&quot;);</span>
<span class="fc" id="L56">        verify(subscriber, Mockito.never()).onError(any(Throwable.class));</span>
<span class="fc" id="L57">        verify(subscriber, times(1)).onComplete();</span>
<span class="fc" id="L58">        verifyNoMoreInteractions(subscriber);</span>
<span class="fc" id="L59">    }</span>

    @Test
    public void testResumeNextWithRuntimeException() {
        // Trigger failure on second element
<span class="fc" id="L64">        TestObservable f = new TestObservable(&quot;one&quot;, &quot;RUNTIMEEXCEPTION&quot;, &quot;two&quot;, &quot;three&quot;);</span>
<span class="fc" id="L65">        Flowable&lt;String&gt; w = Flowable.unsafeCreate(f);</span>
<span class="fc" id="L66">        Flowable&lt;String&gt; resume = Flowable.just(&quot;twoResume&quot;, &quot;threeResume&quot;);</span>
<span class="fc" id="L67">        Flowable&lt;String&gt; flowable = w.onExceptionResumeNext(resume);</span>

<span class="fc" id="L69">        Subscriber&lt;String&gt; subscriber = TestHelper.mockSubscriber();</span>
<span class="fc" id="L70">        flowable.subscribe(subscriber);</span>

        try {
<span class="fc" id="L73">            f.t.join();</span>
<span class="nc" id="L74">        } catch (InterruptedException e) {</span>
<span class="nc" id="L75">            fail(e.getMessage());</span>
<span class="fc" id="L76">        }</span>

<span class="fc" id="L78">        verify(subscriber).onSubscribe((Subscription)any());</span>
<span class="fc" id="L79">        verify(subscriber, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L80">        verify(subscriber, Mockito.never()).onNext(&quot;two&quot;);</span>
<span class="fc" id="L81">        verify(subscriber, Mockito.never()).onNext(&quot;three&quot;);</span>
<span class="fc" id="L82">        verify(subscriber, times(1)).onNext(&quot;twoResume&quot;);</span>
<span class="fc" id="L83">        verify(subscriber, times(1)).onNext(&quot;threeResume&quot;);</span>
<span class="fc" id="L84">        verify(subscriber, Mockito.never()).onError(any(Throwable.class));</span>
<span class="fc" id="L85">        verify(subscriber, times(1)).onComplete();</span>
<span class="fc" id="L86">        verifyNoMoreInteractions(subscriber);</span>
<span class="fc" id="L87">    }</span>

    @Test
    public void testThrowablePassesThru() {
        // Trigger failure on second element
<span class="fc" id="L92">        TestObservable f = new TestObservable(&quot;one&quot;, &quot;THROWABLE&quot;, &quot;two&quot;, &quot;three&quot;);</span>
<span class="fc" id="L93">        Flowable&lt;String&gt; w = Flowable.unsafeCreate(f);</span>
<span class="fc" id="L94">        Flowable&lt;String&gt; resume = Flowable.just(&quot;twoResume&quot;, &quot;threeResume&quot;);</span>
<span class="fc" id="L95">        Flowable&lt;String&gt; flowable = w.onExceptionResumeNext(resume);</span>

<span class="fc" id="L97">        Subscriber&lt;String&gt; subscriber = TestHelper.mockSubscriber();</span>
<span class="fc" id="L98">        flowable.subscribe(subscriber);</span>

        try {
<span class="fc" id="L101">            f.t.join();</span>
<span class="nc" id="L102">        } catch (InterruptedException e) {</span>
<span class="nc" id="L103">            fail(e.getMessage());</span>
<span class="fc" id="L104">        }</span>

<span class="fc" id="L106">        verify(subscriber).onSubscribe((Subscription)any());</span>
<span class="fc" id="L107">        verify(subscriber, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L108">        verify(subscriber, never()).onNext(&quot;two&quot;);</span>
<span class="fc" id="L109">        verify(subscriber, never()).onNext(&quot;three&quot;);</span>
<span class="fc" id="L110">        verify(subscriber, never()).onNext(&quot;twoResume&quot;);</span>
<span class="fc" id="L111">        verify(subscriber, never()).onNext(&quot;threeResume&quot;);</span>
<span class="fc" id="L112">        verify(subscriber, times(1)).onError(any(Throwable.class));</span>
<span class="fc" id="L113">        verify(subscriber, never()).onComplete();</span>
<span class="fc" id="L114">        verifyNoMoreInteractions(subscriber);</span>
<span class="fc" id="L115">    }</span>

    @Test
    public void testErrorPassesThru() {
        // Trigger failure on second element
<span class="fc" id="L120">        TestObservable f = new TestObservable(&quot;one&quot;, &quot;ERROR&quot;, &quot;two&quot;, &quot;three&quot;);</span>
<span class="fc" id="L121">        Flowable&lt;String&gt; w = Flowable.unsafeCreate(f);</span>
<span class="fc" id="L122">        Flowable&lt;String&gt; resume = Flowable.just(&quot;twoResume&quot;, &quot;threeResume&quot;);</span>
<span class="fc" id="L123">        Flowable&lt;String&gt; flowable = w.onExceptionResumeNext(resume);</span>

<span class="fc" id="L125">        Subscriber&lt;String&gt; subscriber = TestHelper.mockSubscriber();</span>
<span class="fc" id="L126">        flowable.subscribe(subscriber);</span>

        try {
<span class="fc" id="L129">            f.t.join();</span>
<span class="nc" id="L130">        } catch (InterruptedException e) {</span>
<span class="nc" id="L131">            fail(e.getMessage());</span>
<span class="fc" id="L132">        }</span>

<span class="fc" id="L134">        verify(subscriber).onSubscribe((Subscription)any());</span>
<span class="fc" id="L135">        verify(subscriber, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L136">        verify(subscriber, never()).onNext(&quot;two&quot;);</span>
<span class="fc" id="L137">        verify(subscriber, never()).onNext(&quot;three&quot;);</span>
<span class="fc" id="L138">        verify(subscriber, never()).onNext(&quot;twoResume&quot;);</span>
<span class="fc" id="L139">        verify(subscriber, never()).onNext(&quot;threeResume&quot;);</span>
<span class="fc" id="L140">        verify(subscriber, times(1)).onError(any(Throwable.class));</span>
<span class="fc" id="L141">        verify(subscriber, never()).onComplete();</span>
<span class="fc" id="L142">        verifyNoMoreInteractions(subscriber);</span>
<span class="fc" id="L143">    }</span>

    @Test
    public void testMapResumeAsyncNext() {
        // Trigger multiple failures
<span class="fc" id="L148">        Flowable&lt;String&gt; w = Flowable.just(&quot;one&quot;, &quot;fail&quot;, &quot;two&quot;, &quot;three&quot;, &quot;fail&quot;);</span>
        // Resume Observable is async
<span class="fc" id="L150">        TestObservable f = new TestObservable(&quot;twoResume&quot;, &quot;threeResume&quot;);</span>
<span class="fc" id="L151">        Flowable&lt;String&gt; resume = Flowable.unsafeCreate(f);</span>

        // Introduce map function that fails intermittently (Map does not prevent this when the observer is a
        //  rx.operator incl onErrorResumeNextViaObservable)
<span class="fc" id="L155">        w = w.map(new Function&lt;String, String&gt;() {</span>
            @Override
            public String apply(String s) {
<span class="fc bfc" id="L158" title="All 2 branches covered.">                if (&quot;fail&quot;.equals(s)) {</span>
<span class="fc" id="L159">                    throw new RuntimeException(&quot;Forced Failure&quot;);</span>
                }
<span class="fc" id="L161">                System.out.println(&quot;BadMapper:&quot; + s);</span>
<span class="fc" id="L162">                return s;</span>
            }
        });

<span class="fc" id="L166">        Flowable&lt;String&gt; flowable = w.onExceptionResumeNext(resume);</span>

<span class="fc" id="L168">        Subscriber&lt;String&gt; subscriber = TestHelper.mockSubscriber();</span>
<span class="fc" id="L169">        flowable.subscribe(subscriber);</span>

        try {
            // if the thread gets started (which it shouldn't if it's working correctly)
<span class="pc bpc" id="L173" title="1 of 2 branches missed.">            if (f.t != null) {</span>
<span class="fc" id="L174">                f.t.join();</span>
            }
<span class="nc" id="L176">        } catch (InterruptedException e) {</span>
<span class="nc" id="L177">            fail(e.getMessage());</span>
<span class="fc" id="L178">        }</span>

<span class="fc" id="L180">        verify(subscriber, times(1)).onNext(&quot;one&quot;);</span>
<span class="fc" id="L181">        verify(subscriber, never()).onNext(&quot;two&quot;);</span>
<span class="fc" id="L182">        verify(subscriber, never()).onNext(&quot;three&quot;);</span>
<span class="fc" id="L183">        verify(subscriber, times(1)).onNext(&quot;twoResume&quot;);</span>
<span class="fc" id="L184">        verify(subscriber, times(1)).onNext(&quot;threeResume&quot;);</span>
<span class="fc" id="L185">        verify(subscriber, Mockito.never()).onError(any(Throwable.class));</span>
<span class="fc" id="L186">        verify(subscriber, times(1)).onComplete();</span>
<span class="fc" id="L187">    }</span>

    @Test
    public void testBackpressure() {
<span class="fc" id="L191">        TestSubscriber&lt;Integer&gt; ts = new TestSubscriber&lt;Integer&gt;();</span>
<span class="fc" id="L192">        Flowable.range(0, 100000)</span>
<span class="fc" id="L193">                .onExceptionResumeNext(Flowable.just(1))</span>
<span class="fc" id="L194">                .observeOn(Schedulers.computation())</span>
<span class="fc" id="L195">                .map(new Function&lt;Integer, Integer&gt;() {</span>
                    int c;

                    @Override
                    public Integer apply(Integer t1) {
<span class="fc bfc" id="L200" title="All 2 branches covered.">                        if (c++ &lt;= 1) {</span>
                            // slow
                            try {
<span class="fc" id="L203">                                Thread.sleep(500);</span>
<span class="nc" id="L204">                            } catch (InterruptedException e) {</span>
<span class="nc" id="L205">                                e.printStackTrace();</span>
<span class="fc" id="L206">                            }</span>
                        }
<span class="fc" id="L208">                        return t1;</span>
                    }

                })
<span class="fc" id="L212">                .subscribe(ts);</span>
<span class="fc" id="L213">        ts.awaitTerminalEvent();</span>
<span class="fc" id="L214">        ts.assertNoErrors();</span>
<span class="fc" id="L215">    }</span>

    private static class TestObservable implements Publisher&lt;String&gt; {

        final String[] values;
        Thread t;

<span class="fc" id="L222">        TestObservable(String... values) {</span>
<span class="fc" id="L223">            this.values = values;</span>
<span class="fc" id="L224">        }</span>

        @Override
        public void subscribe(final Subscriber&lt;? super String&gt; subscriber) {
<span class="fc" id="L228">            subscriber.onSubscribe(new BooleanSubscription());</span>
<span class="fc" id="L229">            System.out.println(&quot;TestObservable subscribed to ...&quot;);</span>
<span class="fc" id="L230">            t = new Thread(new Runnable() {</span>

                @Override
                public void run() {
                    try {
<span class="fc" id="L235">                        System.out.println(&quot;running TestObservable thread&quot;);</span>
<span class="fc bfc" id="L236" title="All 2 branches covered.">                        for (String s : values) {</span>
<span class="fc bfc" id="L237" title="All 2 branches covered.">                            if (&quot;EXCEPTION&quot;.equals(s)) {</span>
<span class="fc" id="L238">                                throw new Exception(&quot;Forced Exception&quot;);</span>
<span class="fc bfc" id="L239" title="All 2 branches covered.">                            } else if (&quot;RUNTIMEEXCEPTION&quot;.equals(s)) {</span>
<span class="fc" id="L240">                                throw new RuntimeException(&quot;Forced RuntimeException&quot;);</span>
<span class="fc bfc" id="L241" title="All 2 branches covered.">                            } else if (&quot;ERROR&quot;.equals(s)) {</span>
<span class="fc" id="L242">                                throw new Error(&quot;Forced Error&quot;);</span>
<span class="fc bfc" id="L243" title="All 2 branches covered.">                            } else if (&quot;THROWABLE&quot;.equals(s)) {</span>
<span class="fc" id="L244">                                throw new Throwable(&quot;Forced Throwable&quot;);</span>
                            }
<span class="fc" id="L246">                            System.out.println(&quot;TestObservable onNext: &quot; + s);</span>
<span class="fc" id="L247">                            subscriber.onNext(s);</span>
                        }
<span class="fc" id="L249">                        System.out.println(&quot;TestObservable onComplete&quot;);</span>
<span class="fc" id="L250">                        subscriber.onComplete();</span>
<span class="fc" id="L251">                    } catch (Throwable e) {</span>
<span class="fc" id="L252">                        System.out.println(&quot;TestObservable onError: &quot; + e);</span>
<span class="fc" id="L253">                        subscriber.onError(e);</span>
<span class="fc" id="L254">                    }</span>
<span class="fc" id="L255">                }</span>

            });
<span class="fc" id="L258">            System.out.println(&quot;starting TestObservable thread&quot;);</span>
<span class="fc" id="L259">            t.start();</span>
<span class="fc" id="L260">            System.out.println(&quot;done starting TestObservable thread&quot;);</span>
<span class="fc" id="L261">        }</span>
    }

    @Test
    public void normalBackpressure() {
<span class="fc" id="L266">        TestSubscriber&lt;Integer&gt; ts = TestSubscriber.create(0);</span>

<span class="fc" id="L268">        PublishProcessor&lt;Integer&gt; pp = PublishProcessor.create();</span>

<span class="fc" id="L270">        pp.onExceptionResumeNext(Flowable.range(3, 2)).subscribe(ts);</span>

<span class="fc" id="L272">        ts.request(2);</span>

<span class="fc" id="L274">        pp.onNext(1);</span>
<span class="fc" id="L275">        pp.onNext(2);</span>
<span class="fc" id="L276">        pp.onError(new TestException(&quot;Forced failure&quot;));</span>

<span class="fc" id="L278">        ts.assertValues(1, 2);</span>
<span class="fc" id="L279">        ts.assertNoErrors();</span>
<span class="fc" id="L280">        ts.assertNotComplete();</span>

<span class="fc" id="L282">        ts.request(2);</span>

<span class="fc" id="L284">        ts.assertValues(1, 2, 3, 4);</span>
<span class="fc" id="L285">        ts.assertNoErrors();</span>
<span class="fc" id="L286">        ts.assertComplete();</span>
<span class="fc" id="L287">    }</span>

}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>