<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>SingleDoOnTest.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">RxJava_2_x$Unnamed.exec</a> &gt; <a href="index.source.html" class="el_package">io.reactivex.internal.operators.single</a> &gt; <span class="el_source">SingleDoOnTest.java</span></div><h1>SingleDoOnTest.java</h1><pre class="source lang-java linenums">/**
 * Copyright (c) 2016-present, RxJava Contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is
 * distributed on an &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See
 * the License for the specific language governing permissions and limitations under the License.
 */

package io.reactivex.internal.operators.single;

import static org.junit.Assert.*;

import java.util.List;

import org.junit.Test;

import io.reactivex.*;
import io.reactivex.disposables.*;
import io.reactivex.exceptions.*;
import io.reactivex.functions.*;
import io.reactivex.internal.functions.Functions;
import io.reactivex.observers.TestObserver;
import io.reactivex.plugins.RxJavaPlugins;
import io.reactivex.subjects.PublishSubject;

<span class="fc" id="L31">public class SingleDoOnTest {</span>

    @Test
    public void doOnDispose() {
<span class="fc" id="L35">        final int[] count = { 0 };</span>

<span class="fc" id="L37">        Single.never().doOnDispose(new Action() {</span>
            @Override
            public void run() throws Exception {
<span class="fc" id="L40">                count[0]++;</span>
<span class="fc" id="L41">            }</span>
<span class="fc" id="L42">        }).test(true);</span>

<span class="fc" id="L44">        assertEquals(1, count[0]);</span>
<span class="fc" id="L45">    }</span>

    @Test
    public void doOnError() {
<span class="fc" id="L49">        final Object[] event = { null };</span>

<span class="fc" id="L51">        Single.error(new TestException()).doOnError(new Consumer&lt;Throwable&gt;() {</span>
            @Override
            public void accept(Throwable e) throws Exception {
<span class="fc" id="L54">                event[0] = e;</span>
<span class="fc" id="L55">            }</span>
        })
<span class="fc" id="L57">        .test();</span>

<span class="fc" id="L59">        assertTrue(event[0].toString(), event[0] instanceof TestException);</span>
<span class="fc" id="L60">    }</span>

    @Test
    public void doOnSubscribe() {
<span class="fc" id="L64">        final int[] count = { 0 };</span>

<span class="fc" id="L66">        Single.never().doOnSubscribe(new Consumer&lt;Disposable&gt;() {</span>
            @Override
            public void accept(Disposable d) throws Exception {
<span class="fc" id="L69">                count[0]++;</span>
<span class="fc" id="L70">            }</span>
<span class="fc" id="L71">        }).test();</span>

<span class="fc" id="L73">        assertEquals(1, count[0]);</span>
<span class="fc" id="L74">    }</span>

    @Test
    public void doOnSuccess() {
<span class="fc" id="L78">        final Object[] event = { null };</span>

<span class="fc" id="L80">        Single.just(1).doOnSuccess(new Consumer&lt;Integer&gt;() {</span>
            @Override
            public void accept(Integer e) throws Exception {
<span class="fc" id="L83">                event[0] = e;</span>
<span class="fc" id="L84">            }</span>
        })
<span class="fc" id="L86">        .test();</span>

<span class="fc" id="L88">        assertEquals(1, event[0]);</span>
<span class="fc" id="L89">    }</span>

    @Test
    public void doOnSubscribeNormal() {
<span class="fc" id="L93">        final int[] count = { 0 };</span>

<span class="fc" id="L95">        Single.just(1).doOnSubscribe(new Consumer&lt;Disposable&gt;() {</span>
            @Override
            public void accept(Disposable d) throws Exception {
<span class="fc" id="L98">                count[0]++;</span>
<span class="fc" id="L99">            }</span>
        })
<span class="fc" id="L101">        .test()</span>
<span class="fc" id="L102">        .assertResult(1);</span>

<span class="fc" id="L104">        assertEquals(1, count[0]);</span>
<span class="fc" id="L105">    }</span>

    @Test
    public void doOnSubscribeError() {
<span class="fc" id="L109">        final int[] count = { 0 };</span>

<span class="fc" id="L111">        Single.error(new TestException()).doOnSubscribe(new Consumer&lt;Disposable&gt;() {</span>
            @Override
            public void accept(Disposable d) throws Exception {
<span class="fc" id="L114">                count[0]++;</span>
<span class="fc" id="L115">            }</span>
        })
<span class="fc" id="L117">        .test()</span>
<span class="fc" id="L118">        .assertFailure(TestException.class);</span>

<span class="fc" id="L120">        assertEquals(1, count[0]);</span>
<span class="fc" id="L121">    }</span>

    @Test
    public void doOnSubscribeJustCrash() {

<span class="fc" id="L126">        Single.just(1).doOnSubscribe(new Consumer&lt;Disposable&gt;() {</span>
            @Override
            public void accept(Disposable d) throws Exception {
<span class="fc" id="L129">                throw new TestException();</span>
            }
        })
<span class="fc" id="L132">        .test()</span>
<span class="fc" id="L133">        .assertFailure(TestException.class);</span>
<span class="fc" id="L134">    }</span>

    @Test
    public void doOnSubscribeErrorCrash() {
<span class="fc" id="L138">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>

        try {
<span class="fc" id="L141">            Single.error(new TestException(&quot;Outer&quot;)).doOnSubscribe(new Consumer&lt;Disposable&gt;() {</span>
                @Override
                public void accept(Disposable d) throws Exception {
<span class="fc" id="L144">                    throw new TestException(&quot;Inner&quot;);</span>
                }
            })
<span class="fc" id="L147">            .test()</span>
<span class="fc" id="L148">            .assertFailureAndMessage(TestException.class, &quot;Inner&quot;);</span>

<span class="fc" id="L150">            TestHelper.assertUndeliverable(errors, 0, TestException.class, &quot;Outer&quot;);</span>
        } finally {
<span class="fc" id="L152">            RxJavaPlugins.reset();</span>
        }

<span class="fc" id="L155">    }</span>

    @Test
    public void onErrorSuccess() {
<span class="fc" id="L159">        final int[] call = { 0 };</span>

<span class="fc" id="L161">        Single.just(1)</span>
<span class="fc" id="L162">        .doOnError(new Consumer&lt;Throwable&gt;() {</span>
            @Override
            public void accept(Throwable v) throws Exception {
<span class="nc" id="L165">                call[0]++;</span>
<span class="nc" id="L166">            }</span>
        })
<span class="fc" id="L168">        .test()</span>
<span class="fc" id="L169">        .assertResult(1);</span>

<span class="fc" id="L171">        assertEquals(0, call[0]);</span>
<span class="fc" id="L172">    }</span>

    @Test
    public void onErrorCrashes() {
<span class="fc" id="L176">        TestObserver&lt;Object&gt; to = Single.error(new TestException(&quot;Outer&quot;))</span>
<span class="fc" id="L177">        .doOnError(new Consumer&lt;Throwable&gt;() {</span>
            @Override
            public void accept(Throwable v) throws Exception {
<span class="fc" id="L180">                throw new TestException(&quot;Inner&quot;);</span>
            }
        })
<span class="fc" id="L183">        .test()</span>
<span class="fc" id="L184">        .assertFailure(CompositeException.class);</span>

<span class="fc" id="L186">        List&lt;Throwable&gt; errors = TestHelper.compositeList(to.errors().get(0));</span>

<span class="fc" id="L188">        TestHelper.assertError(errors, 0, TestException.class, &quot;Outer&quot;);</span>
<span class="fc" id="L189">        TestHelper.assertError(errors, 1, TestException.class, &quot;Inner&quot;);</span>
<span class="fc" id="L190">    }</span>

    @Test
    public void doOnEventThrowsSuccess() {
<span class="fc" id="L194">        Single.just(1)</span>
<span class="fc" id="L195">        .doOnEvent(new BiConsumer&lt;Integer, Throwable&gt;() {</span>
            @Override
            public void accept(Integer v, Throwable e) throws Exception {
<span class="fc" id="L198">                throw new TestException();</span>
            }
        })
<span class="fc" id="L201">        .test()</span>
<span class="fc" id="L202">        .assertFailure(TestException.class);</span>
<span class="fc" id="L203">    }</span>

    @Test
    public void doOnEventThrowsError() {
<span class="fc" id="L207">        TestObserver&lt;Integer&gt; to = Single.&lt;Integer&gt;error(new TestException(&quot;Main&quot;))</span>
<span class="fc" id="L208">        .doOnEvent(new BiConsumer&lt;Integer, Throwable&gt;() {</span>
            @Override
            public void accept(Integer v, Throwable e) throws Exception {
<span class="fc" id="L211">                throw new TestException(&quot;Inner&quot;);</span>
            }
        })
<span class="fc" id="L214">        .test()</span>
<span class="fc" id="L215">        .assertFailure(CompositeException.class);</span>

<span class="fc" id="L217">        List&lt;Throwable&gt; errors = TestHelper.compositeList(to.errors().get(0));</span>

<span class="fc" id="L219">        TestHelper.assertError(errors, 0, TestException.class, &quot;Main&quot;);</span>
<span class="fc" id="L220">        TestHelper.assertError(errors, 1, TestException.class, &quot;Inner&quot;);</span>
<span class="fc" id="L221">    }</span>

    @Test
    public void doOnDisposeDispose() {
<span class="fc" id="L225">        final int[] calls = { 0 };</span>
<span class="fc" id="L226">        TestHelper.checkDisposed(PublishSubject.create().singleOrError().doOnDispose(new Action() {</span>
            @Override
            public void run() throws Exception {
<span class="fc" id="L229">                calls[0]++;</span>
<span class="fc" id="L230">            }</span>
        }));

<span class="fc" id="L233">        assertEquals(1, calls[0]);</span>
<span class="fc" id="L234">    }</span>

    @Test
    public void doOnDisposeSuccess() {
<span class="fc" id="L238">        final int[] calls = { 0 };</span>

<span class="fc" id="L240">        Single.just(1)</span>
<span class="fc" id="L241">        .doOnDispose(new Action() {</span>
            @Override
            public void run() throws Exception {
<span class="nc" id="L244">                calls[0]++;</span>
<span class="nc" id="L245">            }</span>
        })
<span class="fc" id="L247">        .test()</span>
<span class="fc" id="L248">        .assertResult(1);</span>

<span class="fc" id="L250">        assertEquals(0, calls[0]);</span>
<span class="fc" id="L251">    }</span>

    @Test
    public void doOnDisposeError() {
<span class="fc" id="L255">        final int[] calls = { 0 };</span>

<span class="fc" id="L257">        Single.error(new TestException())</span>
<span class="fc" id="L258">        .doOnDispose(new Action() {</span>
            @Override
            public void run() throws Exception {
<span class="nc" id="L261">                calls[0]++;</span>
<span class="nc" id="L262">            }</span>
        })
<span class="fc" id="L264">        .test()</span>
<span class="fc" id="L265">        .assertFailure(TestException.class);</span>

<span class="fc" id="L267">        assertEquals(0, calls[0]);</span>
<span class="fc" id="L268">    }</span>

    @Test
    public void doOnDisposeDoubleOnSubscribe() {
<span class="fc" id="L272">        TestHelper.checkDoubleOnSubscribeSingle(new Function&lt;Single&lt;Object&gt;, SingleSource&lt;Object&gt;&gt;() {</span>
            @Override
            public SingleSource&lt;Object&gt; apply(Single&lt;Object&gt; s) throws Exception {
<span class="fc" id="L275">                return s.doOnDispose(Functions.EMPTY_ACTION);</span>
            }
        });
<span class="fc" id="L278">    }</span>

    @Test
    public void doOnDisposeCrash() {
<span class="fc" id="L282">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L284">            PublishSubject&lt;Integer&gt; ps = PublishSubject.create();</span>

<span class="fc" id="L286">            ps.singleOrError().doOnDispose(new Action() {</span>
                @Override
                public void run() throws Exception {
<span class="fc" id="L289">                    throw new TestException();</span>
                }
            })
<span class="fc" id="L292">            .test()</span>
<span class="fc" id="L293">            .cancel();</span>

<span class="fc" id="L295">            TestHelper.assertUndeliverable(errors, 0, TestException.class);</span>
        } finally {
<span class="fc" id="L297">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L299">    }</span>

    @Test
    public void doOnSuccessErrors() {
<span class="fc" id="L303">        final int[] call = { 0 };</span>

<span class="fc" id="L305">        Single.error(new TestException())</span>
<span class="fc" id="L306">        .doOnSuccess(new Consumer&lt;Object&gt;() {</span>
            @Override
            public void accept(Object v) throws Exception {
<span class="nc" id="L309">                call[0]++;</span>
<span class="nc" id="L310">            }</span>
        })
<span class="fc" id="L312">        .test()</span>
<span class="fc" id="L313">        .assertFailure(TestException.class);</span>

<span class="fc" id="L315">        assertEquals(0, call[0]);</span>
<span class="fc" id="L316">    }</span>

    @Test
    public void doOnSuccessCrash() {
<span class="fc" id="L320">        Single.just(1)</span>
<span class="fc" id="L321">        .doOnSuccess(new Consumer&lt;Integer&gt;() {</span>
            @Override
            public void accept(Integer v) throws Exception {
<span class="fc" id="L324">                throw new TestException();</span>
            }
        })
<span class="fc" id="L327">        .test()</span>
<span class="fc" id="L328">        .assertFailure(TestException.class);</span>
<span class="fc" id="L329">    }</span>

    @Test
    public void onSubscribeCrash() {
<span class="fc" id="L333">        List&lt;Throwable&gt; errors = TestHelper.trackPluginErrors();</span>
        try {
<span class="fc" id="L335">            final Disposable bs = Disposables.empty();</span>

<span class="fc" id="L337">            new Single&lt;Integer&gt;() {</span>
                @Override
                protected void subscribeActual(SingleObserver&lt;? super Integer&gt; observer) {
<span class="fc" id="L340">                    observer.onSubscribe(bs);</span>
<span class="fc" id="L341">                    observer.onError(new TestException(&quot;Second&quot;));</span>
<span class="fc" id="L342">                    observer.onSuccess(1);</span>
<span class="fc" id="L343">                }</span>
            }
<span class="fc" id="L345">            .doOnSubscribe(new Consumer&lt;Disposable&gt;() {</span>
                @Override
                public void accept(Disposable d) throws Exception {
<span class="fc" id="L348">                    throw new TestException(&quot;First&quot;);</span>
                }
            })
<span class="fc" id="L351">            .test()</span>
<span class="fc" id="L352">            .assertFailureAndMessage(TestException.class, &quot;First&quot;);</span>

<span class="fc" id="L354">            assertTrue(bs.isDisposed());</span>

<span class="fc" id="L356">            TestHelper.assertUndeliverable(errors, 0, TestException.class, &quot;Second&quot;);</span>
        } finally {
<span class="fc" id="L358">            RxJavaPlugins.reset();</span>
        }
<span class="fc" id="L360">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.2.201808211720</span></div></body></html>